words = {
    # A (60 terms)
    "algorithm": ["Step-by-step procedure for solving problems", "Set of rules for calculations", "Sequence of computational instructions"],
    "api": ["Application Programming Interface for software communication", "Set of tools for building applications", "Contract between different software components"],
    "application": ["Software program for end users", "App that performs specific tasks", "Program running on devices"],
    "authentication": ["Process of verifying user identity", "Login and credential verification", "Confirming who you are to access systems"],
    "ai": ["Artificial Intelligence mimicking human cognition", "Machines performing intelligent tasks", "Computer systems with learning capabilities"],
    "agile": ["Iterative software development methodology", "Flexible project management approach", "Collaborative development process"],
    "analytics": ["Systematic analysis of data", "Discovery of meaningful patterns", "Data-driven insights generation"],
    "android": ["Google's mobile operating system", "Linux-based OS for smartphones", "Open-source mobile platform"],
    "architecture": ["Structural design of systems", "Blueprint for software organization", "Overall system structure plan"],
    "array": ["Data structure storing elements", "Collection of items in programming", "Ordered series of values"],
    "automation": ["Technology performing tasks without human intervention", "Process self-execution", "Systematic control of operations"],
    "aws": ["Amazon Web Services cloud platform", "Cloud computing services provider", "Amazon's cloud infrastructure"],
    "ajax": ["Asynchronous JavaScript for dynamic web content", "Web development technique", "Data exchange without page reload"],
    "angular": ["Google's web application framework", "TypeScript-based platform", "Front-end development framework"],
    "antivirus": ["Software detecting malicious programs", "Malware protection system", "Computer security application"],
    "app store": ["Digital distribution platform", "Application marketplace", "Software download portal"],
    "artificial intelligence": ["Machine simulation of human intelligence", "Computer systems with cognitive abilities", "Technology enabling smart behavior"],
    "ascii": ["Character encoding standard", "Text representation code", "American Standard Code for Information Interchange"],
    "asset": ["Digital resource in development", "Project file or component", "Development resource item"],
    "attachment": ["File sent with email", "Document included with message", "Email file inclusion"],
    "audio": ["Sound technology", "Digital sound processing", "Computer sound capabilities"],
    "augmented reality": ["Digital overlay on real world", "Enhanced reality technology", "Computer-generated reality enhancement"],
    "autocomplete": ["Text prediction feature", "Input suggestion system", "Word completion technology"],
    "automated testing": ["Software testing without human intervention", "Automatic quality assurance", "Programmatic test execution"],
    "avatar": ["Digital representation of user", "Online character representation", "Virtual identity image"],
    "azure": ["Microsoft cloud platform", "Cloud computing service", "Microsoft Azure services"],

    # B (50 terms)
    "backend": ["Server-side of applications", "Behind-the-scenes software operations", "Database and server management"],
    "bandwidth": ["Data transfer capacity", "Network transmission rate", "Communication channel width"],
    "big data": ["Extremely large datasets", "Complex data requiring special processing", "Massive information volumes"],
    "binary": ["Base-2 number system", "Computer language using 0s and 1s", "Digital representation method"],
    "biometrics": ["Biological characteristics for identification", "Physical trait authentication", "Biological measurement technology"],
    "bit": ["Smallest unit of digital data", "Binary digit (0 or 1)", "Basic computing information unit"],
    "blockchain": ["Distributed digital ledger", "Decentralized transaction record", "Cryptographic chain of blocks"],
    "bot": ["Automated software application", "Program performing repetitive tasks", "Internet robot"],
    "bootstrap": ["Front-end framework for responsive design", "CSS framework for web development", "Twitter's web development toolkit"],
    "bug": ["Software error or flaw", "Programming mistake", "System malfunction cause"],
    "byte": ["Unit of digital information", "Eight bits of data", "Computer storage measurement"],
    "backend developer": ["Server-side programmer", "Database and API specialist", "Server logic creator"],
    "beta": ["Pre-release software version", "Testing phase product", "Early user evaluation stage"],
    "browser": ["Web page viewing software", "Internet navigation application", "HTML rendering program"],
    "backup": ["Data copy for safety", "Information recovery resource", "Duplicate storage for protection"],
    "batch processing": ["Grouped task execution", "Bulk data processing", "Multiple job processing"],
    "beta testing": ["External user testing phase", "Pre-release evaluation", "Real-world software testing"],
    "binary file": ["Non-text computer file", "Executable program format", "Machine-readable file"],
    "bitrate": ["Data transfer speed measurement", "Bits processed per second", "Digital stream rate"],
    "blog": ["Online journal website", "Regular content publication", "Web logging platform"],
    "bluetooth": ["Short-range wireless technology", "Device connectivity standard", "Personal area network protocol"],
    "bookmark": ["Saved web page reference", "Browser location marker", "Website quick access"],
    "broadband": ["High-speed internet connection", "Fast data transmission", "Wide bandwidth networking"],
    "buffer": ["Temporary data storage area", "Memory holding area", "Data transfer intermediate"],
    "bug report": ["Software error documentation", "Problem description document", "Issue tracking report"],

    # C (80 terms)
    "cache": ["High-speed data storage layer", "Temporary memory for fast access", "Frequently-used data storage"],
    "cloud": ["Remote internet servers", "Online computing resources", "Network-hosted services"],
    "code": ["Computer programming instructions", "Software source text", "Programming language statements"],
    "compiler": ["Program translating code to machine language", "Source code to executable converter", "Programming language translator"],
    "cpu": ["Central Processing Unit", "Computer's main processor", "Hardware executing instructions"],
    "cybersecurity": ["Protection against digital attacks", "Information security practice", "Computer system defense"],
    "css": ["Cascading Style Sheets for web design", "Web page styling language", "HTML presentation formatting"],
    "cryptography": ["Secure communication techniques", "Information encryption science", "Data protection methods"],
    "container": ["Software packaging method", "Isolated application environment", "Docker deployment unit"],
    "cookie": ["Website data storage on user's device", "Browser tracking mechanism", "Session information file"],
    "crash": ["Unexpected system failure", "Software termination error", "Program malfunction"],
    "cross platform": ["Software running on multiple systems", "Multi-OS compatible applications", "Platform-independent programs"],
    "cryptocurrency": ["Digital encrypted currency", "Blockchain-based money", "Decentralized digital asset"],
    "cyber attack": ["Digital system intrusion", "Computer network breach", "Online security violation"],
    "data center": ["Facility housing computer systems", "Server storage location", "IT infrastructure hub"],
    "database": ["Organized data collection", "Electronic information storage", "Structured data repository"],
    "debugging": ["Error identification and removal", "Software problem fixing", "Code troubleshooting process"],
    "deployment": ["Software release process", "Application installation", "System implementation"],
    "developer": ["Software creator", "Program writer", "Application builder"],
    "digital": ["Electronic technology representation", "Computer-based systems", "Non-analog technology"],
    "domain": ["Network identification string", "Website address name", "Internet territory"],
    "download": ["Retrieve data from remote system", "File transfer to local device", "Internet file acquisition"],
    "driver": ["Hardware communication software", "Device control program", "Hardware interface"],
    "dynamic": ["Changing or adaptive behavior", "Runtime modification capability", "Real-time adjustment"],
    "data mining": ["Pattern discovery in large datasets", "Knowledge extraction from data", "Information analysis process"],
    "data science": ["Extracting insights from data", "Scientific methods for data analysis", "Information study discipline"],
    "data warehouse": ["Central data repository", "Business intelligence storage", "Historical data collection"],
    "database management system": ["Software for database administration", "Data storage management tool", "DBMS software"],
    "debugger": ["Program for finding errors", "Software testing tool", "Code analysis utility"],
    "decentralized": ["Distributed control system", "No central authority network", "Peer-to-peer organization"],
    "devops": ["Development and operations collaboration", "Software delivery methodology", "CI/CD practices"],
    "digital transformation": ["Technology integration in business", "Digital technology adoption", "Business process modernization"],
    "distributed system": ["Networked computer components", "Multiple computer coordination", "Decentralized computing"],
    "dns": ["Domain Name System", "Internet address translation", "Website name resolution"],
    "docker": ["Containerization platform", "Application packaging tool", "Software container system"],
    "documentation": ["Software instruction writing", "System description documents", "Technical reference materials"],
    "domain name": ["Human-readable web address", "Website identification label", "Internet location name"],
    "dot notation": ["Object property access method", "Programming syntax for hierarchy", "Object member access"],
    "drag and drop": ["GUI element movement method", "Visual interface interaction", "Mouse-based object transfer"],
    "driver update": ["Hardware software upgrade", "Device control improvement", "Hardware compatibility enhancement"],

    # D (continued)
    "data analytics": ["Data examination process", "Information insight derivation", "Statistical data analysis"],
    "data structure": ["Data organization format", "Information storage method", "Computer data arrangement"],
    "deep learning": ["Advanced neural networks", "Machine learning subset", "AI with multiple layers"],
    "desktop application": ["Computer-installed software", "Local machine program", "Non-web application"],
    "digital signature": ["Electronic authentication method", "Digital document verification", "Cryptographic signature"],
    "disk space": ["Storage capacity available", "Hard drive room", "Computer storage availability"],
    "distributed computing": ["Multiple computer task sharing", "Networked processing power", "Collaborative system operation"],
    "dynamic programming": ["Algorithm optimization method", "Problem-solving technique", "Complex problem breakdown"],

    # E (50 terms)
    "encryption": ["Data encoding for security", "Information scrambling", "Privacy protection method"],
    "ethernet": ["Network connection standard", "Wired networking technology", "LAN communication protocol"],
    "etl": ["Extract Transform Load process", "Data integration procedure", "Data warehouse preparation"],
    "ecommerce": ["Online business transactions", "Electronic commerce", "Internet shopping"],
    "edge computing": ["Distributed computing paradigm", "Data processing at network edge", "Decentralized computation"],
    "elasticsearch": ["Search and analytics engine", "Distributed search server", "Document database search"],
    "email": ["Electronic mail system", "Digital message communication", "Internet messaging"],
    "embedded system": ["Computer within larger system", "Dedicated function device", "Special-purpose computing"],
    "emoji": ["Digital pictograph", "Electronic emotion symbol", "Visual character in messaging"],
    "encryption key": ["Cryptographic code", "Data locking mechanism", "Security access code"],
    "endpoint": ["Device connection point", "Network communication terminal", "Remote computing device"],
    "enterprise software": ["Business organization applications", "Corporate-scale programs", "Large business systems"],
    "ethereum": ["Blockchain computing platform", "Cryptocurrency with smart contracts", "Decentralized application platform"],
    "exception": ["Program error handling", "Runtime anomaly", "Software irregularity"],
    "executable": ["Runnable program file", "Software application file", "Computer program binary"],
    "expert system": ["AI decision-making program", "Knowledge-based system", "Problem-solving software"],
    "extranet": ["Private network extension", "External partner network", "Controlled external access"],
    "e-learning": ["Electronic learning", "Online education", "Digital coursework"],
    "emulator": ["Hardware/software imitation", "System simulation program", "Device replication software"],
    "encryption algorithm": ["Data scrambling method", "Cryptographic procedure", "Security encoding process"],
    "error handling": ["Program mistake management", "Exception recovery process", "Fault tolerance mechanism"],
    "ethernet cable": ["Network connection wire", "Internet physical link", "LAN connectivity cable"],
    "event driven": ["Action-response programming", "Trigger-based architecture", "Event-based processing"],
    "export": ["Data output to external format", "File conversion for transfer", "Information extraction process"],
    "extension": ["Software add-on component", "Program functionality enhancement", "Browser plugin"],

    # F (50 terms)
    "firewall": ["Network security system", "Traffic filtering barrier", "Cyber protection wall"],
    "firmware": ["Device embedded software", "Hardware control program", "Permanent software"],
    "framework": ["Software development platform", "Application structure foundation", "Programming toolkit"],
    "frontend": ["User interface development", "Client-side programming", "Visual application part"],
    "full stack": ["Both frontend and backend development", "End-to-end programming", "Complete application development"],
    "function": ["Programming routine", "Reusable code block", "Software procedure"],
    "functional programming": ["Programming paradigm using functions", "Declarative coding style", "Mathematical function-based coding"],
    "fuzzy logic": ["Multi-valued logic system", "Approximate reasoning method", "Non-binary decision making"],
    "file system": ["Data storage organization", "File management structure", "Storage organization method"],
    "filter": ["Data selection mechanism", "Information screening process", "Content separation tool"],
    "firefox": ["Mozilla web browser", "Open-source browser", "Internet navigation software"],
    "flask": ["Python web framework", "Micro web application tool", "Lightweight web development"],
    "flutter": ["Google UI toolkit", "Cross-platform app framework", "Mobile development SDK"],
    "forum": ["Online discussion platform", "Community message board", "Digital conversation space"],
    "fps": ["Frames per second", "Animation smoothness measure", "Video performance metric"],
    "freeware": ["Free software distribution", "No-cost applications", "Gratis programs"],
    "ftp": ["File Transfer Protocol", "Network file sharing", "Data transmission method"],
    "full text search": ["Document content searching", "Complete text examination", "Comprehensive text retrieval"],
    "functional testing": ["Software feature verification", "System requirement testing", "Application behavior checking"],
    "future proof": ["Long-term technology viability", "Forward compatibility design", "Sustainable tech planning"],

    # G (40 terms)
    "git": ["Version control system", "Code change tracking", "Source code management"],
    "github": ["Code hosting platform", "Git repository service", "Developer collaboration site"],
    "gpu": ["Graphics Processing Unit", "Visual computing processor", "Parallel computation hardware"],
    "gui": ["Graphical User Interface", "Visual computer interaction", "Point-and-click interface"],
    "google cloud": ["Google's cloud platform", "GCP computing services", "Google infrastructure services"],
    "graphql": ["API query language", "Data fetching specification", "Runtime data requests"],
    "gaming": ["Video game industry", "Interactive entertainment", "Digital gameplay"],
    "gateway": ["Network connection point", "Protocol translation device", "Network access node"],
    "geolocation": ["Geographic position identification", "Location detection technology", "Positioning services"],
    "gitlab": ["DevOps platform", "Code repository manager", "Software development lifecycle tool"],
    "golang": ["Google programming language", "Go language development", "Systems programming language"],
    "google analytics": ["Web traffic analysis", "Website performance tracking", "Digital analytics service"],
    "gradient descent": ["Machine learning optimization", "Algorithm training method", "Model parameter adjustment"],
    "graph database": ["Relationship-focused data storage", "Network structure database", "Node-connection data model"],
    "grid computing": ["Distributed computing architecture", "Network resource sharing", "Parallel processing system"],
    "gsm": ["Global System for Mobile communications", "Mobile network standard", "Cellular technology"],
    "gui testing": ["User interface verification", "Visual component testing", "Interface functionality checking"],
    "gzip": ["File compression format", "Data size reduction", "Compression algorithm"],
    "game development": ["Video game creation", "Interactive software production", "Entertainment programming"],
    "general ai": ["Human-level artificial intelligence", "Comprehensive AI capability", "Full cognitive machine intelligence"],

    # H (40 terms)
    "html": ["Hypertext Markup Language", "Web page structure language", "Website content markup"],
    "http": ["Hypertext Transfer Protocol", "Web data communication", "Internet information exchange"],
    "https": ["Secure web protocol", "Encrypted HTTP", "Protected internet communication"],
    "hadoop": ["Big data processing framework", "Distributed computing platform", "Large dataset management"],
    "hardware": ["Physical computer components", "Tangible technology devices", "Computer equipment"],
    "hash": ["Data fingerprint function", "Cryptographic digest", "Unique value generation"],
    "hashing": ["Data transformation process", "Fixed-size value creation", "Digital fingerprinting"],
    "hosting": ["Website storage service", "Server provision", "Online content housing"],
    "hybrid app": ["Mixed native-web application", "Cross-platform mobile app", "Multi-environment software"],
    "hypervisor": ["Virtual machine manager", "Hardware virtualization", "VM control program"],
    "hackathon": ["Coding competition event", "Programming marathon", "Software development contest"],
    "hard drive": ["Computer data storage device", "Magnetic storage hardware", "Permanent data storage"],
    "header": ["Document metadata section", "Data packet information", "Message beginning part"],
    "heatmap": ["Data visualization technique", "Color-coded information display", "Intensity mapping"],
    "hexadecimal": ["Base-16 number system", "16-digit numerical representation", "Programming number format"],
    "homepage": ["Main website page", "Site entry point", "Primary web location"],
    "host": ["Network service provider", "Computer offering services", "System running applications"],
    "hotfix": ["Urgent software patch", "Emergency bug repair", "Critical update"],
    "html5": ["Modern web standard", "Advanced HTML version", "Current web markup"],
    "http2": ["Web protocol upgrade", "Faster HTTP version", "Enhanced web communication"],

    # I (60 terms)
    "iot": ["Internet of Things", "Networked physical devices", "Smart connected objects"],
    "ip address": ["Internet Protocol address", "Network device identifier", "Digital location label"],
    "ide": ["Integrated Development Environment", "Programming software suite", "Code editing platform"],
    "ios": ["Apple mobile operating system", "iPhone/iPad platform", "Apple device OS"],
    "ipv6": ["Internet Protocol version 6", "Modern IP addressing", "Expanded internet addresses"],
    "iteration": ["Repeated process cycle", "Development repetition", "Sequential improvement"],
    "integration": ["System combination process", "Component connection", "Software unification"],
    "interface": ["System interaction point", "Connection boundary", "Communication surface"],
    "internet": ["Global computer network", "Worldwide web system", "Digital information network"],
    "intranet": ["Private organizational network", "Internal company network", "Local restricted network"],
    "iot device": ["Internet-connected physical object", "Smart networked device", "Web-enabled thing"],
    "ip camera": ["Internet Protocol camera", "Network-connected camera", "Web-based surveillance"],
    "isp": ["Internet Service Provider", "Internet access company", "Web connectivity service"],
    "it": ["Information Technology", "Computer systems field", "Digital technology sector"],
    "image processing": ["Digital picture manipulation", "Computer vision preparation", "Graphic analysis"],
    "in memory database": ["RAM-based data storage", "Memory-resident database", "Fast access data system"],
    "indexing": ["Data organization for search", "Information cataloging", "Quick retrieval preparation"],
    "infrastructure": ["Technology foundation", "System underlying structure", "IT operational base"],
    "instant messaging": ["Real-time text communication", "Live chat technology", "Immediate message exchange"],
    "internet explorer": ["Microsoft web browser", "Legacy browser application", "Windows default browser"],
    "interoperability": ["System cooperation ability", "Cross-platform compatibility", "Technology integration capability"],
    "intrusion detection": ["Security breach monitoring", "Unauthorized access detection", "Network protection system"],
    "ip telephony": ["Internet protocol phone calls", "Digital voice communication", "Network-based telephony"],
    "ipv4": ["Original Internet Protocol", "Traditional IP addressing", "Legacy internet protocol"],
    "it support": ["Technology assistance service", "Computer help services", "Technical problem resolution"],

    # J (30 terms)
    "java": ["Programming language platform", "Object-oriented language", "Write once run anywhere"],
    "javascript": ["Web scripting language", "Client-side programming", "Browser interaction language"],
    "json": ["JavaScript Object Notation", "Data interchange format", "Lightweight data structure"],
    "jquery": ["JavaScript library", "DOM manipulation tool", "Web development framework"],
    "jvm": ["Java Virtual Machine", "Java runtime environment", "Bytecode execution platform"],
    "jdbc": ["Java Database Connectivity", "Database connection API", "Java data access"],
    "jupyter": ["Interactive computing platform", "Data science notebook", "Code documentation tool"],
    "job scheduler": ["Task automation system", "Process timing controller", "Workload management"],
    "join": ["Database table combination", "SQL data merging", "Relational connection"],
    "jailbreak": ["iOS restriction removal", "Apple device unlocking", "Mobile OS modification"],
    "jar": ["Java Archive file", "Java package format", "Executable Java bundle"],
    "java ee": ["Java Enterprise Edition", "Large-scale Java platform", "Business application framework"],
    "javascript framework": ["JS development structure", "Web application toolkit", "Client-side programming platform"],
    "jit": ["Just-In-Time compilation", "Runtime code optimization", "Dynamic compilation"],
    "job": ["Scheduled computing task", "Background process", "Automated work unit"],

    # K (30 terms)
    "kernel": ["Operating system core", "System resource manager", "Computer central control"],
    "key": ["Database identifier", "Cryptography code", "Unique data reference"],
    "keyboard": ["Computer input device", "Typing hardware", "Character entry tool"],
    "keyframe": ["Animation reference point", "Motion definition frame", "Timeline marker"],
    "keyword": ["Search term identifier", "Programming reserved word", "Content classification term"],
    "kill": ["Process termination", "Program stop command", "Task ending"],
    "knowledge base": ["Information repository", "Organized data collection", "Reference database"],
    "kubernetes": ["Container orchestration system", "Docker management platform", "Cloud deployment automation"],
    "kvm": ["Keyboard Video Mouse switch", "Multi-computer control", "Hardware sharing device"],
    "key value pair": ["Data storage format", "Simple database structure", "Attribute-value combination"],
    "keylogger": ["Keystroke recording software", "Input monitoring program", "Typing activity tracker"],
    "kilobyte": ["Digital storage unit", "File size measure", "Data amount measurement"],
    "kiosk": ["Interactive information terminal", "Self-service station", "Public access computer"],
    "knowledge graph": ["Information network structure", "Semantic data representation", "Entity relationship map"],
    "kpi": ["Key Performance Indicator", "Success measurement metric", "Business metric"],

    # L (50 terms)
    "linux": ["Open-source operating system", "Unix-like OS kernel", "Free software platform"],
    "laravel": ["PHP web framework", "MVC development platform", "Modern PHP framework"],
    "load balancing": ["Traffic distribution method", "Server workload sharing", "Performance optimization"],
    "library": ["Code collection for reuse", "Programming resource package", "Software component archive"],
    "loop": ["Programming repetition structure", "Code iteration mechanism", "Repeated execution block"],
    "latency": ["Network delay time", "Data transfer lag", "Response time measurement"],
    "local storage": ["Browser data storage", "Client-side data saving", "Web storage API"],
    "logging": ["System activity recording", "Event tracking process", "Application monitoring"],
    "machine learning": ["AI pattern recognition", "Algorithmic learning from data", "Predictive model training"],
    "microservices": ["Modular application architecture", "Independent service components", "Distributed system design"],
    "mobile app": ["Smartphone application", "Mobile device software", "Portable application"],
    "maintenance": ["System upkeep activities", "Software updating process", "Technology care"],
    "malware": ["Malicious software programs", "Harmful computer code", "Digital threat software"],
    "metadata": ["Data about data", "Information description", "Content attributes"],
    "middleware": ["Software connection layer", "Application integration tool", "System bridge software"],

    # M (70 terms)
    "machine learning": ["AI pattern recognition", "Algorithmic learning from data", "Predictive model training"],
    "microservices": ["Modular application architecture", "Independent service components", "Distributed system design"],
    "mobile app": ["Smartphone application", "Mobile device software", "Portable application"],
    "maintenance": ["System upkeep activities", "Software updating process", "Technology care"],
    "malware": ["Malicious software programs", "Harmful computer code", "Digital threat software"],
    "metadata": ["Data about data", "Information description", "Content attributes"],
    "middleware": ["Software connection layer", "Application integration tool", "System bridge software"],
    "migration": ["System transfer process", "Data moving procedure", "Platform transition"],
    "mobile first": ["Mobile design priority", "Smartphone-focused development", "Responsive design approach"],
    "modem": ["Internet connection device", "Network signal converter", "Digital communication hardware"],
    "module": ["Software component unit", "Program section", "Code package"],
    "monitoring": ["System observation process", "Performance tracking", "Application watching"],
    "multithreading": ["Parallel task execution", "Simultaneous processing", "Concurrent programming"],
    "mvc": ["Model View Controller architecture", "Software design pattern", "Separation of concerns pattern"],
    "mysql": ["Relational database system", "Open-source database", "SQL database management"],
    "mac address": ["Hardware identifier", "Network interface address", "Device physical address"],
    "machine code": ["Computer native language", "Binary instructions", "Processor direct commands"],
    "mainframe": ["Large computer system", "Enterprise computing platform", "High-performance server"],
    "malware analysis": ["Threat software examination", "Virus investigation", "Security code review"],
    "marketplace": ["Digital product platform", "Online store for apps", "Software distribution center"],
    "memory": ["Computer data storage", "RAM working space", "Temporary information holding"],
    "microprocessor": ["Computer processor chip", "CPU integrated circuit", "Central processing unit"],
    "mobile device": ["Portable computing equipment", "Smartphone or tablet", "Handheld technology"],
    "model": ["Data representation structure", "System simulation", "Conceptual framework"],
    "modulation": ["Signal conversion process", "Data transmission method", "Waveform alteration"],
    "monitor": ["Computer display screen", "System performance tracker", "Observation tool"],
    "motherboard": ["Main computer circuit board", "System component connector", "Computer central board"],
    "mouse": ["Computer pointing device", "Cursor control hardware", "Input navigation tool"],
    "multimedia": ["Multiple media content", "Audio-video materials", "Digital content combination"],
    "multitasking": ["Multiple job handling", "Simultaneous task execution", "Parallel operation"],

    # N (40 terms)
    "neural network": ["AI brain simulation", "Machine learning model", "Pattern recognition system"],
    "node": ["Network connection point", "JavaScript runtime environment", "System component"],
    "npm": ["Node package manager", "JavaScript library repository", "Code package system"],
    "network": ["Computer connection system", "Communication infrastructure", "Device interconnection"],
    "nosql": ["Non-relational database", "Flexible data storage", "Modern database approach"],
    "native app": ["Platform-specific application", "OS-optimized software", "Device-native program"],
    "navigation": ["Interface movement system", "User journey guidance", "Menu structure design"],
    "networking": ["Computer connection practice", "Device communication setup", "Network establishment"],
    "normalization": ["Database organization process", "Data structure optimization", "Information standardization"],
    "notification": ["System alert message", "User information update", "Application message"],
    "null": ["Empty value representation", "No data indicator", "Missing information marker"],
    "namespace": ["Code organization container", "Naming context scope", "Programming identifier space"],
    "natural language processing": ["Computer human language understanding", "Text analysis technology", "Linguistic AI capability"],
    "near field communication": ["Short-range wireless technology", "Contactless data exchange", "NFC proximity communication"],
    "network security": ["Connection protection measures", "Cyber defense systems", "Network threat prevention"],
    "node js": ["JavaScript runtime platform", "Server-side JavaScript", "Asynchronous programming environment"],
    "nosql database": ["Non-tabular data storage", "Flexible schema database", "Modern data management"],
    "notification system": ["Alert distribution mechanism", "Message delivery platform", "User update service"],

    # O (40 terms)
    "open source": ["Publicly available code", "Community-developed software", "Free access programming"],
    "operating system": ["Computer management software", "Device operation platform", "System resource manager"],
    "optimization": ["Performance improvement process", "Efficiency enhancement", "System tuning"],
    "oracle": ["Database company and products", "Enterprise software provider", "Relational database system"],
    "output": ["System result data", "Processed information delivery", "Program production"],
    "object": ["Programming data entity", "Code instance with properties", "OOP fundamental unit"],
    "object oriented programming": ["Code organization methodology", "Object-based development", "OOP software paradigm"],
    "offline": ["Disconnected operation mode", "No internet access state", "Local-only functionality"],
    "online": ["Internet-connected state", "Network availability", "Web-access mode"],
    "open api": ["Public programming interface", "Accessible software connection", "Available integration point"],
    "operational technology": ["Industrial control systems", "Physical device management", "OT infrastructure"],
    "optical fiber": ["Light-based data transmission", "High-speed network cable", "Fiber optic technology"],
    "optimizer": ["Performance improvement tool", "Efficiency enhancement software", "System tuning program"],
    "orchestration": ["Automated workflow management", "Process coordination system", "Service arrangement"],
    "organic search": ["Natural search results", "Non-paid web findings", "Algorithmic search outcomes"],
    "output device": ["Information presentation hardware", "Result display equipment", "Data presentation tool"],
    "overflow": ["Data capacity exceeded", "Storage limit surpassed", "Buffer exceeded error"],

    # P (80 terms)
    "python": ["Programming language", "High-level coding language", "Versatile development tool"],
    "programming": ["Software creation process", "Code writing activity", "Computer instruction development"],
    "protocol": ["Communication standard", "Data exchange rules", "Network interaction specification"],
    "php": ["Web development language", "Server-side scripting", "Dynamic website programming"],
    "package": ["Software distribution unit", "Code bundle", "Program collection"],
    "patch": ["Software update fix", "Bug correction release", "Program repair"],
    "performance": ["System speed and efficiency", "Software operation quality", "Application responsiveness"],
    "permission": ["Access authorization", "System rights grant", "Security privilege"],
    "platform": ["Technology foundation", "Software running environment", "Development base"],
    "plugin": ["Software extension component", "Program add-on feature", "Application enhancement"],
    "port": ["Network connection point", "Computer interface socket", "Communication endpoint"],
    "privacy": ["Data protection right", "Information confidentiality", "Personal security"],
    "process": ["Program execution instance", "Running application", "Computer task"],
    "processor": ["Computer calculation unit", "CPU hardware component", "Data processing chip"],
    "production": ["Live software environment", "Operational system state", "Active deployment"],
    "program": ["Software application", "Computer instructions", "Executable code"],
    "project": ["Development initiative", "Software creation effort", "Technology work plan"],
    "protocol": ["Communication standard rules", "Data format specification", "Network interaction method"],
    "proxy": ["Intermediate server system", "Network request forwarder", "Connection intermediary"],
    "public cloud": ["Shared computing services", "Multi-tenant cloud platform", "Available internet services"],
    "push notification": ["Mobile app message alert", "Server-sent user message", "Application update notification"],
    "password": ["Security access code", "Authentication credential", "User verification string"],
    "pattern": ["Design template approach", "Recurring solution format", "Programming model"],
    "payment gateway": ["Online transaction processor", "E-commerce payment system", "Digital money transfer service"],
    "peer to peer": ["Direct device communication", "Distributed network model", "Equal node interaction"],
    "penetration testing": ["Security vulnerability assessment", "Authorized system hacking", "Cyber defense evaluation"],
    "peripheral": ["External computer device", "Additional hardware component", "Computer attachment"],
    "permission": ["Access rights setting", "Security authorization", "System privilege"],
    "persistence": ["Data permanent storage", "Information retention", "Long-term saving"],
    "phishing": ["Fraudulent email attacks", "Identity theft attempt", "Deceptive online communication"],
    "pipeline": ["Data processing sequence", "Workflow stages", "Automated process chain"],
    "pixel": ["Screen display unit", "Image element point", "Digital picture component"],
    "platform as a service": ["Cloud application platform", "PaaS development environment", "Online platform services"],
    "portability": ["System transfer capability", "Cross-platform compatibility", "Software mobility"],
    "power supply": ["Computer electricity source", "Device energy provider", "Hardware power unit"],
    "private cloud": ["Dedicated cloud services", "Single-tenant cloud platform", "Exclusive cloud infrastructure"],
    "procedure": ["Program method routine", "Software process steps", "Execution sequence"],
    "process management": ["Program execution control", "Task administration", "System process handling"],
    "product owner": ["Development requirement manager", "Project feature decision maker", "Agile team role"],
    "programming language": ["Software development syntax", "Computer instruction format", "Code writing system"],

    # Q (20 terms)
    "query": ["Database information request", "Search question", "Data retrieval command"],
    "quality assurance": ["Software testing process", "Quality verification", "Product validation"],
    "quantum computing": ["Advanced computing technology", "Quantum physics processing", "Next-generation computation"],
    "queue": ["Data waiting structure", "Process line sequence", "Task ordering system"],
    "quick response code": ["Matrix barcode format", "QR scanable code", "Mobile information code"],
    "quality control": ["Product standard verification", "Quality maintenance process", "Standard compliance checking"],
    "quantum bit": ["Quantum computing unit", "Qubit information measure", "Quantum state representation"],
    "query language": ["Database question syntax", "Information request format", "Data retrieval grammar"],
    "query optimization": ["Database search improvement", "Search performance enhancement", "Query speed tuning"],
    "quick start": ["Rapid beginning process", "Fast initiation guide", "Accelerated beginning"],

    # R (60 terms)
    "react": ["JavaScript UI library", "Frontend development framework", "Component-based library"],
    "responsive design": ["Adaptive web layout", "Multi-device compatibility", "Flexible interface design"],
    "rest": ["Web service architecture", "Representational State Transfer", "API design principle"],
    "router": ["Network traffic director", "Internet connection manager", "Data packet forwarder"],
    "runtime": ["Program execution period", "Software operation time", "Application running state"],
    "raspberry pi": ["Small computer board", "Educational computing device", "DIY project platform"],
    "real time": ["Immediate processing", "Instant system response", "Live data handling"],
    "recursion": ["Self-calling function", "Repeated process invocation", "Programming repetition technique"],
    "refresh": ["Content update action", "Screen redisplay", "Data reload"],
    "registry": ["System configuration database", "Windows settings store", "Operating system settings"],
    "regression": ["Statistical analysis method", "Relationship modeling", "Machine learning technique"],
    "release": ["Software version publication", "Product deployment", "Application launch"],
    "remote": ["Distant access capability", "Network connection operation", "Off-site control"],
    "render": ["Visual display generation", "Image creation process", "Content presentation"],
    "repository": ["Code storage location", "Version control storage", "Software archive"],
    "reset": ["System restoration", "Default state return", "Configuration clearance"],
    "resolution": ["Screen detail level", "Display pixel density", "Image clarity measure"],
    "resource": ["System available asset", "Computing capability component", "Available tool or asset"],
    "restart": ["System reboot process", "Program reload", "Fresh start"],
    "restore": ["Data recovery process", "Backup retrieval", "System return to previous state"],
    "retina display": ["High-resolution Apple screen", "Sharp visual technology", "Apple display standard"],
    "reverse engineering": ["Product analysis technique", "System deconstruction", "Technology examination"],
    "robot": ["Automated machine system", "Programmable mechanical device", "AI physical agent"],
    "robotics": ["Robot technology field", "Automation engineering", "Machine system science"],
    "root": ["System administrator level", "Highest access privilege", "Superuser authority"],
    "router": ["Network connection device", "Internet traffic manager", "Home network center"],
    "rss": ["Web content syndication", "News feed format", "Content distribution standard"],
    "ruby": ["Programming language", "Dynamic coding language", "Web development platform"],
    "rust": ["Systems programming language", "Memory-safe language", "Modern performance language"],

    # S (80 terms)
    "sql": ["Database query language", "Structured Query Language", "Data management language"],
    "server": ["Network service provider", "Computer offering resources", "Central data host"],
    "software": ["Computer programs", "Digital applications", "Electronic instructions"],
    "security": ["System protection measures", "Cyber threat prevention", "Information safety"],
    "scalability": ["System growth capability", "Performance expansion ability", "Load handling capacity"],
    "script": ["Automation program code", "Lightweight programming", "Task automation file"],
    "sdk": ["Software Development Kit", "Programming tool collection", "Application building tools"],
    "search engine": ["Web information finder", "Internet content locator", "Online search system"],
    "serverless": ["Cloud execution model", "No-server architecture", "Function as a Service"],
    "session": ["User interaction period", "Temporary connection state", "Activity time frame"],
    "settings": ["System configuration options", "User preferences", "Application adjustments"],
    "shareware": ["Trial software distribution", "Limited free software", "Try-before-buy programs"],
    "shell": ["System command interface", "Terminal environment", "Command processor"],
    "smartphone": ["Mobile computing device", "Advanced cell phone", "Pocket computer"],
    "social media": ["Online community platforms", "Digital networking sites", "Internet social networks"],
    "software engineering": ["Professional programming discipline", "Systematic software development", "Structured application creation"],
    "spam": ["Unwanted digital messages", "Bulk unsolicited email", "Electronic junk mail"],
    "spreadsheet": ["Data table software", "Numerical analysis tool", "Grid calculation program"],
    "spyware": ["Secret monitoring software", "Covert data collection", "Privacy invasion program"],
    "ssl": ["Secure Sockets Layer", "Encryption security protocol", "Web security certificate"],
    "stack": ["Technology combination", "Software layer collection", "Development tool set"],
    "storage": ["Data retention capacity", "Information holding space", "Digital memory"],
    "streaming": ["Continuous data delivery", "Real-time media playback", "Progressive content transfer"],
    "subnet": ["Network division segment", "IP address subgroup", "Network partition"],
    "supercomputer": ["High-performance computer", "Advanced calculation system", "Scientific computing machine"],
    "support": ["Technical assistance service", "Problem resolution help", "User aid provision"],
    "syntax": ["Programming language grammar", "Code structure rules", "Language format specification"],
    "system": ["Integrated technology collection", "Coordinated component set", "Organized computer setup"],

    # T (60 terms)
    "typescript": ["JavaScript with types", "Microsoft programming language", "Typed JS superset"],
    "tablet": ["Portable touchscreen device", "Mobile computing platform", "Handheld computer"],
    "tag": ["Content label marker", "Information categorization", "Data identification"],
    "task": ["Computing work unit", "Program execution job", "System operation"],
    "template": ["Document format pattern", "Reusable design structure", "Pre-made layout"],
    "test": ["Software verification process", "Quality checking method", "Bug detection procedure"],
    "thread": ["Program execution path", "Processing sequence", "Concurrent task line"],
    "token": ["Security access object", "Authentication piece", "Digital permission unit"],
    "tool": ["Software utility program", "Development assistance application", "Technical helper"],
    "touchscreen": ["Direct display interaction", "Touch interface technology", "Screen contact input"],
    "transaction": ["Database operation unit", "Business process action", "Complete data exchange"],
    "transmission": ["Data sending process", "Information transfer", "Network communication"],
    "troubleshooting": ["Problem solving process", "Issue resolution method", "Fault diagnosis"],
    "tuple": ["Ordered data sequence", "Fixed element collection", "Programming data structure"],
    "twitter": ["Social media platform", "Microblogging service", "Short message network"],
    "type": ["Data category classification", "Programming variable kind", "Information format"],

    # U (40 terms)
    "ui": ["User Interface", "Application visual design", "User interaction surface"],
    "ux": ["User Experience", "Overall user interaction quality", "Human-computer interaction design"],
    "ubuntu": ["Linux operating system", "Open-source OS distribution", "Debian-based Linux"],
    "upload": ["Data sending to server", "File transfer to remote system", "Information sharing to network"],
    "url": ["Web address location", "Uniform Resource Locator", "Internet site identifier"],
    "usb": ["Universal Serial Bus", "Device connection standard", "Computer peripheral interface"],
    "user": ["System operator person", "Software consumer", "Technology end-user"],
    "user agent": ["Software acting for user", "Browser identification", "Client application"],
    "user story": ["Development requirement description", "Feature explanation format", "Agile development tool"],
    "utility": ["System helper program", "Computer tool application", "Software assistance program"],

    # V (40 terms)
    "virtual machine": ["Software computer emulation", "Virtualized environment", "Guest operating system"],
    "vpn": ["Virtual Private Network", "Secure internet connection", "Encrypted network tunnel"],
    "virus": ["Malicious computer program", "Self-replicating malware", "Digital infection code"],
    "virtual reality": ["Immersive digital environment", "Computer-generated world", "VR simulated experience"],
    "version control": ["Code change management", "Software revision tracking", "Development history system"],
    "video": ["Moving visual content", "Digital motion pictures", "Electronic animation"],
    "voice recognition": ["Speech understanding technology", "Voice command processing", "Audio input interpretation"],
    "vulnerability": ["Security weakness point", "System flaw exposure", "Cyber attack opportunity"],
    "validation": ["Data correctness checking", "Input verification process", "Information accuracy confirmation"],
    "variable": ["Programming data container", "Value storage location", "Changeable information holder"],

    # W (50 terms)
    "web development": ["Website creation process", "Online application building", "Internet software development"],
    "website": ["Internet location collection", "Web page group", "Online presence site"],
    "windows": ["Microsoft operating system", "PC desktop platform", "Graphical OS environment"],
    "wireless": ["Connection without cables", "Radio-based networking", "Cordless technology"],
    "workflow": ["Process sequence automation", "Task procedure system", "Business process management"],
    "web server": ["Internet content provider", "Website hosting computer", "Online service system"],
    "web application": ["Browser-based software", "Online program interface", "Internet accessible application"],
    "wi-fi": ["Wireless networking technology", "Radio internet connection", "Wireless local network"],
    "worm": ["Self-propagating malware", "Network spreading virus", "Replicating malicious code"],
    "web design": ["Website visual creation", "Online interface design", "Internet page layout"],
    "web hosting": ["Website storage service", "Online content provision", "Internet site rental"],
    "web service": ["Online software component", "Internet accessible function", "Web API service"],
    "web socket": ["Real-time web communication", "Persistent connection protocol", "Live data exchange"],
    "white hat": ["Ethical security hacker", "Authorized penetration tester", "Good intention hacker"],
    "widget": ["Interface component element", "GUI control object", "Visual program piece"],
    "wiki": ["Collaborative website platform", "Community-editable content", "Group knowledge base"],
    "wireframe": ["Interface layout sketch", "Basic design structure", "Visual planning outline"],
    "workstation": ["Professional computer system", "High-performance desktop", "Specialized computing station"],
    "world wide web": ["Global information system", "Internet content network", "Web page collection"],

    # X (10 terms)
    "xml": ["Extensible Markup Language", "Data format standard", "Structured document format"],
    "xss": ["Cross-site scripting attack", "Web security vulnerability", "Browser injection attack"],
    "xcode": ["Apple development environment", "iOS programming IDE", "Mac application builder"],
    "xamarin": ["Microsoft mobile framework", "Cross-platform app development", "C# mobile programming"],
    "xhtml": ["Extended HTML version", "Strict HTML standard", "XML-based HTML"],

    # Y (10 terms)
    "yaml": ["Human-readable data format", "Configuration file language", "Data serialization standard"],
    "youtube": ["Video sharing platform", "Online video service", "Google video website"],

    # Z (10 terms)
    "zero day": ["Unknown software vulnerability", "Unpatched security flaw", "Newly discovered exploit"],
    "zip": ["File compression format", "Data archive format", "Compressed file format"],
    "zombie": ["Compromised computer system", "Botnet controlled machine", "Hacked network device"]
}

