words = {
    # A (60 termes)
    "algorithme": ["Procédure étape par étape pour résoudre des problèmes", "Ensemble de règles pour les calculs", "Séquence d'instructions informatiques"],
    "api": ["Interface de programmation pour la communication logicielle", "Ensemble d'outils pour créer des applications", "Contrat entre différents composants logiciels"],
    "application": ["Programme logiciel pour les utilisateurs finaux", "Logiciel qui exécute des tâches spécifiques", "Programme fonctionnant sur des appareils"],
    "authentification": ["Processus de vérification de l'identité utilisateur", "Vérification de connexion et d'identification", "Confirmation de votre identité pour accéder aux systèmes"],
    "ia": ["Intelligence Artificielle imitant la cognition humaine", "Machines exécutant des tâches intelligentes", "Systèmes informatiques avec capacités d'apprentissage"],
    "agile": ["Méthodologie de développement logiciel itérative", "Approche flexible de gestion de projet", "Processus de développement collaboratif"],
    "analytique": ["Analyse systématique des données", "Découverte de modèles significatifs", "Génération d'informations basées sur les données"],
    "android": ["Système d'exploitation mobile de Google", "OS basé sur Linux pour smartphones", "Plateforme mobile open-source"],
    "architecture": ["Conception structurelle des systèmes", "Plan d'organisation du logiciel", "Plan de structure globale du système"],
    "tableau": ["Structure de données stockant des éléments", "Collection d'éléments en programmation", "Série ordonnée de valeurs"],
    "automatisation": ["Technologie exécutant des tâches sans intervention humaine", "Auto-exécution des processus", "Contrôle systématique des opérations"],
    "aws": ["Plateforme cloud Amazon Web Services", "Fournisseur de services cloud computing", "Infrastructure cloud d'Amazon"],
    "ajax": ["JavaScript asynchrone pour contenu web dynamique", "Technique de développement web", "Échange de données sans rechargement de page"],
    "angular": ["Framework d'application web de Google", "Plateforme basée sur TypeScript", "Framework de développement frontend"],
    "antivirus": ["Logiciel détectant les programmes malveillants", "Système de protection contre les malwares", "Application de sécurité informatique"],
    "magasin d'applications": ["Plateforme de distribution numérique", "Marché d'applications", "Portail de téléchargement de logiciels"],
    "intelligence artificielle": ["Simulation machine de l'intelligence humaine", "Systèmes informatiques avec capacités cognitives", "Technologie permettant un comportement intelligent"],
    "ascii": ["Standard de codage de caractères", "Code de représentation textuelle", "Code américain standard pour l'échange d'information"],
    "actif": ["Ressource numérique en développement", "Fichier ou composant de projet", "Élément de ressource de développement"],
    "pièce jointe": ["Fichier envoyé avec email", "Document inclus avec message", "Inclusion de fichier dans email"],
    "audio": ["Technologie sonore", "Traitement sonore numérique", "Capacités sonores de l'ordinateur"],
    "réalité augmentée": ["Superposition numérique sur le monde réel", "Technologie de réalité améliorée", "Amélioration de réalité générée par ordinateur"],
    "saisie automatique": ["Fonction de prédiction de texte", "Système de suggestion de saisie", "Technologie de complétion de mots"],
    "test automatisé": ["Test logiciel sans intervention humaine", "Assurance qualité automatique", "Exécution de test programmatique"],
    "avatar": ["Représentation numérique de l'utilisateur", "Représentation de personnage en ligne", "Image d'identité virtuelle"],
    "azure": ["Plateforme cloud Microsoft", "Service de cloud computing", "Services Microsoft Azure"],

    # B (50 termes)
    "backend": ["Côté serveur des applications", "Opérations logicielles en arrière-plan", "Gestion de base de données et serveur"],
    "bande passante": ["Capacité de transfert de données", "Débit de transmission réseau", "Largeur du canal de communication"],
    "big data": ["Jeux de données extrêmement volumineux", "Données complexes nécessitant un traitement spécial", "Volumes massifs d'information"],
    "binaire": ["Système numérique base-2", "Langage informatique utilisant 0 et 1", "Méthode de représentation numérique"],
    "biométrie": ["Caractéristiques biologiques pour identification", "Authentification par traits physiques", "Technologie de mesure biologique"],
    "bit": ["Plus petite unité de données numériques", "Chiffre binaire (0 ou 1)", "Unité d'information informatique de base"],
    "blockchain": ["Registre numérique distribué", "Enregistrement de transaction décentralisé", "Chaîne cryptographique de blocs"],
    "bot": ["Application logicielle automatisée", "Programme exécutant des tâches répétitives", "Robot internet"],
    "bootstrap": ["Framework frontend pour design responsive", "Framework CSS pour développement web", "Boîte à outils de développement web de Twitter"],
    "bug": ["Erreur ou défaut logiciel", "Erreur de programmation", "Cause de dysfonctionnement système"],
    "octet": ["Unité d'information numérique", "Huit bits de données", "Mesure de stockage informatique"],
    "développeur backend": ["Programmeur côté serveur", "Spécialiste base de données et API", "Créateur de logique serveur"],
    "bêta": ["Version logicielle pré-livraison", "Produit en phase de test", "Stade d'évaluation utilisateur précoce"],
    "navigateur": ["Logiciel de visualisation de pages web", "Application de navigation internet", "Programme de rendu HTML"],
    "sauvegarde": ["Copie de données pour sécurité", "Ressource de récupération d'information", "Stockage dupliqué pour protection"],
    "traitement par lots": ["Exécution groupée de tâches", "Traitement de données en masse", "Traitement multiple de travaux"],
    "test bêta": ["Phase de test utilisateur externe", "Évaluation pré-livraison", "Test logiciel en conditions réelles"],
    "fichier binaire": ["Fichier informatique non-textuel", "Format de programme exécutable", "Fichier lisible par machine"],
    "débit binaire": ["Mesure de vitesse de transfert de données", "Bits traités par seconde", "Débit de flux numérique"],
    "blog": ["Site web journal en ligne", "Publication régulière de contenu", "Plateforme de blogage web"],
    "bluetooth": ["Technologie sans fil courte portée", "Standard de connectivité d'appareils", "Protocole de réseau personnel"],
    "signet": ["Référence de page web sauvegardée", "Marqueur d'emplacement navigateur", "Accès rapide au site web"],
    "haut débit": ["Connexion internet haute vitesse", "Transmission rapide de données", "Réseautage large bande"],
    "tampon": ["Zone de stockage temporaire de données", "Zone de maintien en mémoire", "Intermédiaire de transfert de données"],
    "rapport de bug": ["Documentation d'erreur logicielle", "Document de description de problème", "Rapport de suivi d'incident"],

    # C (80 termes)
    "cache": ["Couche de stockage haute vitesse", "Mémoire temporaire pour accès rapide", "Stockage de données fréquemment utilisées"],
    "cloud": ["Serveurs internet distants", "Ressources informatiques en ligne", "Services hébergés en réseau"],
    "code": ["Instructions de programmation informatique", "Texte source du logiciel", "Instructions de langage de programmation"],
    "compilateur": ["Programme traduisant le code en langage machine", "Convertisseur code source vers exécutable", "Traducteur de langage de programmation"],
    "processeur": ["Unité Centrale de Traitement", "Processeur principal de l'ordinateur", "Matériel exécutant les instructions"],
    "cybersécurité": ["Protection contre les attaques numériques", "Pratique de sécurité de l'information", "Défense du système informatique"],
    "css": ["Feuilles de style en cascade pour design web", "Langage de style de pages web", "Formatage de présentation HTML"],
    "cryptographie": ["Techniques de communication sécurisée", "Science du chiffrement d'information", "Méthodes de protection des données"],
    "conteneur": ["Méthode d'empaquetage logiciel", "Environnement d'application isolé", "Unité de déploiement Docker"],
    "cookie": ["Stockage de données de site web sur appareil utilisateur", "Mécanisme de suivi navigateur", "Fichier d'information de session"],
    "plantage": ["Défaillance système inattendue", "Erreur de terminaison logicielle", "Dysfonctionnement de programme"],
    "multiplateforme": ["Logiciel fonctionnant sur plusieurs systèmes", "Applications compatibles multi-OS", "Programmes indépendants de la plateforme"],
    "cryptomonnaie": ["Monnaie numérique chiffrée", "Argent basé sur blockchain", "Actif numérique décentralisé"],
    "cyberattaque": ["Intrusion dans le système numérique", "Violation de réseau informatique", "Infraction de sécurité en ligne"],
    "centre de données": ["Installation hébergeant des systèmes informatiques", "Emplacement de stockage serveur", "Hub d'infrastructure IT"],
    "base de données": ["Collection organisée de données", "Stockage électronique d'information", "Dépôt de données structurées"],
    "débogage": ["Identification et suppression d'erreurs", "Correction de problèmes logiciels", "Processus de dépannage de code"],
    "déploiement": ["Processus de publication logicielle", "Installation d'application", "Mise en œuvre de système"],
    "développeur": ["Créateur de logiciels", "Rédacteur de programmes", "Constructeur d'applications"],
    "numérique": ["Représentation technologique électronique", "Systèmes basés sur ordinateur", "Technologie non-analogique"],
    "domaine": ["Chaîne d'identification réseau", "Nom d'adresse de site web", "Territoire internet"],
    "téléchargement": ["Récupération de données depuis système distant", "Transfert de fichier vers appareil local", "Acquisition de fichier internet"],
    "pilote": ["Logiciel de communication matériel", "Programme de contrôle d'appareil", "Interface matérielle"],
    "dynamique": ["Comportement changeant ou adaptatif", "Capacité de modification en temps d'exécution", "Ajustement en temps réel"],
    "exploration de données": ["Découverte de modèles dans de grands jeux de données", "Extraction de connaissances des données", "Processus d'analyse d'information"],
    "science des données": ["Extraction d'informations des données", "Méthodes scientifiques d'analyse de données", "Discipline d'étude de l'information"],
    "entrepôt de données": ["Dépôt central de données", "Stockage d'intelligence d'affaires", "Collection de données historiques"],
    "système de gestion de base de données": ["Logiciel d'administration de base de données", "Outil de gestion de stockage de données", "Logiciel SGBD"],
    "débogueur": ["Programme de recherche d'erreurs", "Outil de test logiciel", "Utilitaire d'analyse de code"],
    "décentralisé": ["Système de contrôle distribué", "Réseau sans autorité centrale", "Organisation pair-à-pair"],
    "devops": ["Collaboration développement et opérations", "Méthodologie de livraison logicielle", "Pratiques CI/CD"],
    "transformation numérique": ["Intégration technologique dans les affaires", "Adoption de technologie numérique", "Modernisation des processus métier"],
    "système distribué": ["Composants informatiques en réseau", "Coordination d'ordinateurs multiples", "Informatique décentralisée"],
    "dns": ["Système de Noms de Domaine", "Traduction d'adresse internet", "Résolution de nom de site web"],
    "docker": ["Plateforme de conteneurisation", "Outil d'empaquetage d'applications", "Système de conteneurs logiciels"],
    "documentation": ["Rédaction d'instructions logicielles", "Documents de description système", "Matériels de référence technique"],
    "nom de domaine": ["Adresse web lisible par humain", "Étiquette d'identification de site web", "Nom d'emplacement internet"],
    "notation pointée": ["Méthode d'accès aux propriétés d'objet", "Syntaxe de programmation pour hiérarchie", "Accès aux membres d'objet"],
    "glisser-déposer": ["Méthode de mouvement d'éléments GUI", "Interaction d'interface visuelle", "Transfert d'objets basé sur souris"],
    "mise à jour pilote": ["Mise à niveau logicielle matérielle", "Amélioration de contrôle d'appareil", "Amélioration de compatibilité matérielle"],

    # D (suite)
    "analyse de données": ["Processus d'examen des données", "Dérivation d'informations", "Analyse statistique de données"],
    "structure de données": ["Format d'organisation des données", "Méthode de stockage d'information", "Agencement de données informatiques"],
    "apprentissage profond": ["Réseaux neuronaux avancés", "Sous-ensemble d'apprentissage automatique", "IA avec multiples couches"],
    "application de bureau": ["Logiciel installé sur ordinateur", "Programme de machine locale", "Application non-web"],
    "signature numérique": ["Méthode d'authentification électronique", "Vérification de document numérique", "Signature cryptographique"],
    "espace disque": ["Capacité de stockage disponible", "Espace disque dur", "Disponibilité de stockage informatique"],
    "informatique distribuée": ["Partage de tâches multi-ordinateurs", "Puissance de traitement en réseau", "Opération système collaborative"],
    "programmation dynamique": ["Méthode d'optimisation d'algorithme", "Technique de résolution de problèmes", "Décomposition de problème complexe"],

    # E (50 termes)
    "chiffrement": ["Codage de données pour sécurité", "Brouillage d'information", "Méthode de protection de vie privée"],
    "ethernet": ["Standard de connexion réseau", "Technologie de réseautage filaire", "Protocole de communication LAN"],
    "etl": ["Processus Extract Transform Load", "Procédure d'intégration de données", "Préparation d'entrepôt de données"],
    "commerce électronique": ["Transactions commerciales en ligne", "Commerce électronique", "Achats internet"],
    "informatique en périphérie": ["Paradigme d'informatique distribué", "Traitement de données en périphérie réseau", "Calcul décentralisé"],
    "elasticsearch": ["Moteur de recherche et analytique", "Serveur de recherche distribué", "Recherche de base de données document"],
    "email": ["Système de courrier électronique", "Communication de message numérique", "Messagerie internet"],
    "système embarqué": ["Ordinateur dans système plus large", "Appareil à fonction dédiée", "Informatique à usage spécial"],
    "emoji": ["Pictogramme numérique", "Symbole d'émotion électronique", "Caractère visuel en messagerie"],
    "clé de chiffrement": ["Code cryptographique", "Mécanisme de verrouillage de données", "Code d'accès sécurité"],
    "point de terminaison": ["Point de connexion d'appareil", "Terminal de communication réseau", "Appareil informatique distant"],
    "logiciel d'entreprise": ["Applications d'organisation commerciale", "Programmes à l'échelle d'entreprise", "Systèmes de grande entreprise"],
    "ethereum": ["Plateforme informatique blockchain", "Cryptomonnaie avec contrats intelligents", "Plateforme d'application décentralisée"],
    "exception": ["Gestion d'erreur de programme", "Anomalie d'exécution", "Irrégularité logicielle"],
    "exécutable": ["Fichier programme exécutable", "Fichier d'application logicielle", "Binaire de programme informatique"],
    "système expert": ["Programme de prise de décision IA", "Système basé sur la connaissance", "Logiciel de résolution de problèmes"],
    "extranet": ["Extension de réseau privé", "Réseau partenaire externe", "Accès externe contrôlé"],
    "apprentissage en ligne": ["Apprentissage électronique", "Éducation en ligne", "Cours numérique"],
    "émulateur": ["Imitation matériel/logiciel", "Programme de simulation système", "Logiciel de réplication d'appareil"],
    "algorithme de chiffrement": ["Méthode de brouillage de données", "Procédure cryptographique", "Processus d'encodage sécurité"],
    "gestion des erreurs": ["Gestion des fautes de programme", "Processus de récupération d'exception", "Mécanisme de tolérance aux pannes"],
    "câble ethernet": ["Fil de connexion réseau", "Lien physique internet", "Câble de connectivité LAN"],
    "événementiel": ["Programmation action-réponse", "Architecture basée sur déclencheurs", "Traitement basé sur événements"],
    "exportation": ["Sortie de données vers format externe", "Conversion de fichier pour transfert", "Processus d'extraction d'information"],
    "extension": ["Composant add-on logiciel", "Amélioration de fonctionnalité programme", "Plugin navigateur"],

    # F (50 termes)
    "pare-feu": ["Système de sécurité réseau", "Barrière de filtrage de trafic", "Mur de protection cybernétique"],
    "micrologiciel": ["Logiciel intégré d'appareil", "Programme de contrôle matériel", "Logiciel permanent"],
    "framework": ["Plateforme de développement logiciel", "Fondation de structure d'application", "Boîte à outils de programmation"],
    "frontend": ["Développement d'interface utilisateur", "Programmation côté client", "Partie visuelle d'application"],
    "full stack": ["Développement frontend et backend", "Programmation de bout en bout", "Développement d'application complet"],
    "fonction": ["Routine de programmation", "Bloc de code réutilisable", "Procédure logicielle"],
    "programmation fonctionnelle": ["Paradigme de programmation utilisant fonctions", "Style de codage déclaratif", "Codage basé sur fonctions mathématiques"],
    "logique floue": ["Système logique multi-valeurs", "Méthode de raisonnement approximatif", "Prise de décision non-binaire"],
    "système de fichiers": ["Organisation de stockage de données", "Structure de gestion de fichiers", "Méthode d'organisation de stockage"],
    "filtre": ["Mécanisme de sélection de données", "Processus de criblage d'information", "Outil de séparation de contenu"],
    "firefox": ["Navigateur web Mozilla", "Navigateur open-source", "Logiciel de navigation internet"],
    "flask": ["Framework web Python", "Outil micro application web", "Développement web léger"],
    "flutter": ["Kit d'interface utilisateur Google", "Framework d'application multiplateforme", "SDK de développement mobile"],
    "forum": ["Plateforme de discussion en ligne", "Tableau de message communautaire", "Espace de conversation numérique"],
    "ips": ["Images par seconde", "Mesure de fluidité d'animation", "Métrique de performance vidéo"],
    "graticiel": ["Distribution logicielle gratuite", "Applications sans coût", "Programmes gratuits"],
    "ftp": ["Protocole de Transfert de Fichier", "Partage de fichier réseau", "Méthode de transmission de données"],
    "recherche en texte intégral": ["Recherche de contenu document", "Examen complet de texte", "Récupération textuelle complète"],
    "test fonctionnel": ["Vérification de fonctionnalité logicielle", "Test d'exigence système", "Vérification de comportement d'application"],
    "pérenne": ["Viabilité technologique long terme", "Conception de compatibilité future", "Planification technologique durable"],

    # G (40 termes)
    "git": ["Système de contrôle de version", "Suivi des modifications de code", "Gestion de code source"],
    "github": ["Plateforme d'hébergement de code", "Service de dépôt Git", "Site de collaboration développeur"],
    "gpu": ["Unité de Traitement Graphique", "Processeur de calcul visuel", "Matériel de calcul parallèle"],
    "interface graphique": ["Interface Utilisateur Graphique", "Interaction visuelle ordinateur", "Interface pointer-cliquer"],
    "google cloud": ["Plateforme cloud Google", "Services cloud GCP", "Services d'infrastructure Google"],
    "graphql": ["Langage de requête API", "Spécification de récupération de données", "Demandes de données runtime"],
    "jeu vidéo": ["Industrie du jeu vidéo", "Divertissement interactif", "Gameplay numérique"],
    "passerelle": ["Point de connexion réseau", "Appareil de traduction de protocole", "Nœud d'accès réseau"],
    "géolocalisation": ["Identification de position géographique", "Technologie de détection d'emplacement", "Services de positionnement"],
    "gitlab": ["Plateforme DevOps", "Gestionnaire de dépôt de code", "Outil de cycle de vie développement logiciel"],
    "golang": ["Langage de programmation Google", "Développement langage Go", "Langage de programmation système"],
    "google analytics": ["Analyse de trafic web", "Suivi de performance site web", "Service d'analyse numérique"],
    "descente de gradient": ["Optimisation d'apprentissage automatique", "Méthode d'entraînement d'algorithme", "Ajustement de paramètre de modèle"],
    "base de données graphe": ["Stockage de données axé relations", "Base de données structure réseau", "Modèle de données nœud-connexion"],
    "informatique en grille": ["Architecture d'informatique distribuée", "Partage de ressources réseau", "Système de traitement parallèle"],
    "gsm": ["Système Global pour Communications Mobiles", "Standard de réseau mobile", "Technologie cellulaire"],
    "test d'interface graphique": ["Vérification d'interface utilisateur", "Test de composant visuel", "Vérification de fonctionnalité d'interface"],
    "gzip": ["Format de compression de fichier", "Réduction de taille de données", "Algorithme de compression"],
    "développement de jeu": ["Création de jeu vidéo", "Production de logiciel interactif", "Programmation de divertissement"],
    "ia générale": ["Intelligence artificielle niveau humain", "Capacité IA complète", "Intelligence machine cognitive complète"],

    # H (40 termes)
    "html": ["Langage de Balisage Hypertexte", "Langage de structure de page web", "Balisage de contenu de site web"],
    "http": ["Protocole de Transfert Hypertexte", "Communication de données web", "Échange d'information internet"],
    "https": ["Protocole web sécurisé", "HTTP chiffré", "Communication internet protégée"],
    "hadoop": ["Framework de traitement big data", "Plateforme d'informatique distribuée", "Gestion de grands jeux de données"],
    "matériel": ["Composants physiques d'ordinateur", "Appareils technologiques tangibles", "Équipement informatique"],
    "hachage": ["Fonction d'empreinte de données", "Condensé cryptographique", "Génération de valeur unique"],
    "fonction de hachage": ["Processus de transformation de données", "Création de valeur taille fixe", "Empreinte digitale numérique"],
    "hébergement": ["Service de stockage de site web", "Provision de serveur", "Hébergement de contenu en ligne"],
    "application hybride": ["Application mixte native-web", "Application mobile multiplateforme", "Logiciel multi-environnement"],
    "hyperviseur": ["Gestionnaire de machine virtuelle", "Virtualisation de matériel", "Programme de contrôle VM"],
    "hackathon": ["Événement de compétition de codage", "Marathon de programmation", "Concours de développement logiciel"],
    "disque dur": ["Appareil de stockage de données informatique", "Matériel de stockage magnétique", "Stockage de données permanent"],
    "en-tête": ["Section métadonnées document", "Information de paquet de données", "Partie début message"],
    "carte thermique": ["Technique de visualisation de données", "Affichage d'information codé couleur", "Cartographie d'intensité"],
    "hexadécimal": ["Système numérique base-16", "Représentation numérique 16 chiffres", "Format numérique programmation"],
    "page d'accueil": ["Page principale site web", "Point d'entrée site", "Emplacement web primaire"],
    "hôte": ["Fournisseur de service réseau", "Ordinateur offrant des services", "Système exécutant des applications"],
    "correctif urgent": ["Correctif logiciel urgent", "Réparation de bug d'urgence", "Mise à jour critique"],
    "html5": ["Standard web moderne", "Version HTML avancée", "Balisage web actuel"],
    "http2": ["Mise à niveau protocole web", "Version HTTP plus rapide", "Communication web améliorée"],

    # I (60 termes)
    "iot": ["Internet des Objets", "Appareils physiques en réseau", "Objets connectés intelligents"],
    "adresse ip": ["Adresse de Protocole Internet", "Identifiant d'appareil réseau", "Étiquette d'emplacement numérique"],
    "ide": ["Environnement de Développement Intégré", "Suite logicielle de programmation", "Plateforme d'édition de code"],
    "ios": ["Système d'exploitation mobile Apple", "Plateforme iPhone/iPad", "OS d'appareil Apple"],
    "ipv6": ["Protocole Internet version 6", "Adressage IP moderne", "Adresses internet étendues"],
    "itération": ["Cycle de processus répété", "Répétition de développement", "Amélioration séquentielle"],
    "intégration": ["Processus de combinaison système", "Connexion de composant", "Unification logicielle"],
    "interface": ["Point d'interaction système", "Frontière de connexion", "Surface de communication"],
    "internet": ["Réseau informatique global", "Système web mondial", "Réseau d'information numérique"],
    "intranet": ["Réseau organisationnel privé", "Réseau interne d'entreprise", "Réseau local restreint"],
    "appareil iot": ["Objet physique connecté internet", "Appareil en réseau intelligent", "Objet compatible web"],
    "caméra ip": ["Caméra Protocole Internet", "Caméra connectée réseau", "Surveillance basée web"],
    "fai": ["Fournisseur d'Accès Internet", "Entreprise d'accès internet", "Service de connectivité web"],
    "informatique": ["Technologies de l'Information", "Domaine des systèmes informatiques", "Secteur technologie numérique"],
    "traitement d'image": ["Manipulation d'image numérique", "Préparation vision ordinateur", "Analyse graphique"],
    "base de données en mémoire": ["Stockage de données en RAM", "Base de données résidente mémoire", "Système de données accès rapide"],
    "indexation": ["Organisation de données pour recherche", "Catalogage d'information", "Préparation de récupération rapide"],
    "infrastructure": ["Fondation technologique", "Structure sous-jacente système", "Base opérationnelle IT"],
    "messagerie instantanée": ["Communication texte temps réel", "Technologie de chat en direct", "Échange de message immédiat"],
    "internet explorer": ["Navigateur web Microsoft", "Application navigateur héritée", "Navigateur par défaut Windows"],
    "interopérabilité": ["Capacité de coopération système", "Compatibilité multiplateforme", "Capacité d'intégration technologique"],
    "détection d'intrusion": ["Surveillance de violation sécurité", "Détection d'accès non autorisé", "Système de protection réseau"],
    "téléphonie ip": ["Appels téléphoniques protocole internet", "Communication vocale numérique", "Téléphonie basée réseau"],
    "ipv4": ["Protocole Internet original", "Adressage IP traditionnel", "Protocole internet hérité"],
    "support informatique": ["Service d'assistance technologique", "Services d'aide informatique", "Résolution de problème technique"],

    # J (30 termes)
    "java": ["Plateforme langage de programmation", "Langage orienté objet", "Écrire une fois exécuter partout"],
    "javascript": ["Langage de script web", "Programmation côté client", "Langage d'interaction navigateur"],
    "json": ["Notation Objet JavaScript", "Format d'échange de données", "Structure de données légère"],
    "jquery": ["Bibliothèque JavaScript", "Outil de manipulation DOM", "Framework de développement web"],
    "jvm": ["Machine Virtuelle Java", "Environnement d'exécution Java", "Plateforme d'exécution bytecode"],
    "jdbc": ["Connectivité Java Base de Données", "API de connexion base de données", "Accès données Java"],
    "jupyter": ["Plateforme de calcul interactif", "Cahier de science des données", "Outil de documentation de code"],
    "ordonnanceur de tâches": ["Système d'automatisation de tâches", "Contrôleur de timing processus", "Gestionnaire de charge de travail"],
    "jointure": ["Combinaison de tables base de données", "Fusion de données SQL", "Connexion relationnelle"],
    "jailbreak": ["Suppression restriction iOS", "Déverrouillage appareil Apple", "Modification OS mobile"],
    "jar": ["Fichier Archive Java", "Format de package Java", "Bundle Java exécutable"],
    "java ee": ["Édition Entreprise Java", "Plateforme Java grande échelle", "Framework d'application métier"],
    "framework javascript": ["Structure de développement JS", "Boîte à outils application web", "Plateforme de programmation côté client"],
    "jit": ["Compilation Juste-À-Temps", "Optimisation de code runtime", "Compilation dynamique"],
    "tâche": ["Tâche informatique planifiée", "Processus d'arrière-plan", "Unité de travail automatisée"],

    # K (30 termes)
    "noyau": ["Cœur du système d'exploitation", "Gestionnaire de ressources système", "Contrôle central ordinateur"],
    "clé": ["Identifiant base de données", "Code cryptographique", "Référence de données unique"],
    "clavier": ["Périphérique de saisie ordinateur", "Matériel de frappe", "Outil de saisie de caractères"],
    "image clé": ["Point de référence d'animation", "Image de définition mouvement", "Marqueur de timeline"],
    "mot-clé": ["Identifiant de terme recherche", "Mot réservé programmation", "Terme de classification contenu"],
    "terminer": ["Terminaison de processus", "Commande d'arrêt programme", "Fin de tâche"],
    "base de connaissances": ["Dépôt d'information", "Collection organisée de données", "Base de données référence"],
    "kubernetes": ["Système d'orchestration de conteneurs", "Plateforme de gestion Docker", "Automatisation de déploiement cloud"],
    "kvm": ["Commutateur Clavier Vidéo Souris", "Contrôle multi-ordinateurs", "Appareil de partage matériel"],
    "paire clé-valeur": ["Format de stockage de données", "Structure base de données simple", "Combinaison attribut-valeur"],
    "enregistreur de frappe": ["Logiciel d'enregistrement de frappes", "Programme de surveillance saisie", "Traqueur d'activité de frappe"],
    "kilooctet": ["Unité de stockage numérique", "Mesure de taille fichier", "Mesure de quantité données"],
    "kiosque": ["Terminal d'information interactif", "Station libre-service", "Ordinateur d'accès public"],
    "graphe de connaissances": ["Structure de réseau d'information", "Représentation de données sémantique", "Carte de relation d'entités"],
    "kpi": ["Indicateur Clé de Performance", "Métrique de mesure succès", "Métrique commerciale"],

    # L (50 termes)
    "linux": ["Système d'exploitation open-source", "Noyau OS type Unix", "Plateforme logicielle libre"],
    "laravel": ["Framework web PHP", "Plateforme de développement MVC", "Framework PHP moderne"],
    "répartition de charge": ["Méthode de distribution trafic", "Partage charge serveur", "Optimisation performance"],
    "bibliothèque": ["Collection de code pour réutilisation", "Package ressource programmation", "Archive composant logiciel"],
    "boucle": ["Structure de répétition programmation", "Mécanisme d'itération code", "Bloc d'exécution répétée"],
    "latence": ["Temps de délai réseau", "Décalage transfert données", "Mesure temps réponse"],
    "stockage local": ["Stockage données navigateur", "Sauvegarde données côté client", "API stockage web"],
    "journalisation": ["Enregistrement activité système", "Processus de suivi événements", "Surveillance application"],
    "apprentissage automatique": ["Reconnaissance de pattern IA", "Apprentissage algorithmique données", "Entraînement modèle prédictif"],
    "microservices": ["Architecture d'application modulaire", "Composants service indépendants", "Conception système distribué"],
    "application mobile": ["Application smartphone", "Logiciel appareil mobile", "Application portable"],
    "maintenance": ["Activités d'entretien système", "Processus mise à jour logicielle", "Entretien technologie"],
    "logiciel malveillant": ["Programmes logiciels malveillants", "Code informatique nuisible", "Logiciel menace numérique"],
    "métadonnées": ["Données sur les données", "Description d'information", "Attributs de contenu"],
    "middleware": ["Couche de connexion logicielle", "Outil d'intégration d'application", "Logiciel pont système"],

    # M (70 termes)
    "apprentissage automatique": ["Reconnaissance de pattern IA", "Apprentissage algorithmique données", "Entraînement modèle prédictif"],
    "microservices": ["Architecture d'application modulaire", "Composants service indépendants", "Conception système distribué"],
    "application mobile": ["Application smartphone", "Logiciel appareil mobile", "Application portable"],
    "maintenance": ["Activités d'entretien système", "Processus mise à jour logicielle", "Entretien technologie"],
    "logiciel malveillant": ["Programmes logiciels malveillants", "Code informatique nuisible", "Logiciel menace numérique"],
    "métadonnées": ["Données sur les données", "Description d'information", "Attributs de contenu"],
    "middleware": ["Couche de connexion logicielle", "Outil d'intégration d'application", "Logiciel pont système"],
    "migration": ["Processus transfert système", "Procédure déplacement données", "Transition plateforme"],
    "mobile first": ["Priorité conception mobile", "Développement axé smartphone", "Approche design responsive"],
    "modem": ["Appareil connexion internet", "Convertisseur signal réseau", "Matériel communication numérique"],
    "module": ["Unité composant logiciel", "Section programme", "Package code"],
    "surveillance": ["Processus d'observation système", "Suivi performance", "Observation application"],
    "multithreading": ["Exécution tâche parallèle", "Traitement simultané", "Programmation concurrente"],
    "mvc": ["Architecture Modèle Vue Contrôleur", "Modèle de conception logicielle", "Pattern séparation préoccupations"],
    "mysql": ["Système base de données relationnelle", "Base de données open-source", "Gestion base de données SQL"],
    "adresse mac": ["Identifiant matériel", "Adresse interface réseau", "Adresse physique appareil"],
    "code machine": ["Langage natif ordinateur", "Instructions binaires", "Commandes directes processeur"],
    "mainframe": ["Système ordinateur large", "Plateforme informatique entreprise", "Serveur haute performance"],
    "analyse de logiciel malveillant": ["Examen logiciel menace", "Investigation virus", "Revue code sécurité"],
    "place de marché": ["Plateforme produit numérique", "Boutique en ligne applications", "Centre distribution logicielle"],
    "mémoire": ["Stockage données ordinateur", "Espace travail RAM", "Maintien information temporaire"],
    "microprocesseur": ["Puce processeur ordinateur", "Circuit intégré CPU", "Unité centrale traitement"],
    "appareil mobile": ["Équipement informatique portable", "Smartphone ou tablette", "Technologie portable"],
    "modèle": ["Structure représentation données", "Simulation système", "Cadre conceptuel"],
    "modulation": ["Processus conversion signal", "Méthode transmission données", "Altération onde"],
    "moniteur": ["Écran d'affichage ordinateur", "Traqueur performance système", "Outil d'observation"],
    "carte mère": ["Carte circuit principale ordinateur", "Connecteur composant système", "Carte centrale ordinateur"],
    "souris": ["Périphérique pointage ordinateur", "Matériel contrôle curseur", "Outil navigation saisie"],
    "multimédia": ["Contenu multiple médias", "Matériels audio-vidéo", "Combinaison contenu numérique"],
    "multitâche": ["Gestion multiple travaux", "Exécution tâche simultanée", "Opération parallèle"],

    # N (40 termes)
    "réseau neuronal": ["Simulation cerveau IA", "Modèle apprentissage automatique", "Système reconnaissance pattern"],
    "nœud": ["Point connexion réseau", "Environnement d'exécution JavaScript", "Composant système"],
    "npm": ["Gestionnaire de package Node", "Dépôt bibliothèque JavaScript", "Système package code"],
    "réseau": ["Système connexion ordinateurs", "Infrastructure communication", "Interconnexion appareils"],
    "nosql": ["Base de données non-relationnelle", "Stockage données flexible", "Approche base de données moderne"],
    "application native": ["Application spécifique plateforme", "Logiciel optimisé OS", "Programme natif appareil"],
    "navigation": ["Système mouvement interface", "Guidage parcours utilisateur", "Conception structure menu"],
    "mise en réseau": ["Pratique connexion ordinateurs", "Configuration communication appareils", "Établissement réseau"],
    "normalisation": ["Processus organisation base données", "Optimisation structure données", "Standardisation information"],
    "notification": ["Message alerte système", "Mise à jour information utilisateur", "Message application"],
    "nul": ["Représentation valeur vide", "Indicateur absence données", "Marqueur information manquante"],
    "espace de noms": ["Conteneur organisation code", "Portée contexte nommage", "Espace identifiant programmation"],
    "traitement langage naturel": ["Compréhension langage humain ordinateur", "Technologie analyse texte", "Capacité IA linguistique"],
    "communication champ proche": ["Technologie sans fil courte portée", "Échange données sans contact", "Communication proximité NFC"],
    "sécurité réseau": ["Mesures protection connexion", "Systèmes défense cybernétique", "Prévention menace réseau"],
    "node js": ["Plateforme d'exécution JavaScript", "JavaScript côté serveur", "Environnement programmation asynchrone"],
    "base de données nosql": ["Stockage données non-tabulaire", "Base de données schéma flexible", "Gestion données moderne"],
    "système de notification": ["Mécanisme distribution alertes", "Plateforme livraison messages", "Service mise à jour utilisateur"],

    # O (40 termes)
    "open source": ["Code disponible publiquement", "Logiciel développé communauté", "Programmation accès libre"],
    "système d'exploitation": ["Logiciel gestion ordinateur", "Plateforme opération appareil", "Gestionnaire ressources système"],
    "optimisation": ["Processus amélioration performance", "Augmentation efficacité", "Ajustement système"],
    "oracle": ["Entreprise base de données produits", "Fournisseur logiciel entreprise", "Système base de données relationnelle"],
    "sortie": ["Données résultat système", "Livraison information traitée", "Production programme"],
    "objet": ["Entité données programmation", "Instance code avec propriétés", "Unité fondamentale POO"],
    "programmation orientée objet": ["Méthodologie organisation code", "Développement basé objets", "Paradigme logiciel POO"],
    "hors ligne": ["Mode opération déconnecté", "État sans accès internet", "Fonctionnalité locale uniquement"],
    "en ligne": ["État connecté internet", "Disponibilité réseau", "Mode accès web"],
    "api ouverte": ["Interface programmation publique", "Connexion logicielle accessible", "Point intégration disponible"],
    "technologie opérationnelle": ["Systèmes contrôle industriel", "Gestion appareils physiques", "Infrastructure OT"],
    "fibre optique": ["Transmission données basée lumière", "Câble réseau haute vitesse", "Technologie fibre optique"],
    "optimiseur": ["Outil amélioration performance", "Logiciel augmentation efficacité", "Programme ajustement système"],
    "orchestration": ["Gestion workflow automatisé", "Système coordination processus", "Arrangement service"],
    "recherche organique": ["Résultats recherche naturels", "Trouvailles web non payantes", "Résultats recherche algorithmique"],
    "périphérique de sortie": ["Matériel présentation information", "Équipement affichage résultats", "Outil présentation données"],
    "débordement": ["Capacité données dépassée", "Limite stockage surpassée", "Erreur tampon dépassé"],

    # P (80 termes)
    "python": ["Langage de programmation", "Langage de codage haut niveau", "Outil de développement polyvalent"],
    "programmation": ["Processus création logicielle", "Activité écriture code", "Développement instructions ordinateur"],
    "protocole": ["Standard communication", "Règles échange données", "Spécification interaction réseau"],
    "php": ["Langage développement web", "Script côté serveur", "Programmation site web dynamique"],
    "package": ["Unité distribution logicielle", "Bundle code", "Collection programmes"],
    "correctif": ["Mise à jour correctif logiciel", "Version correction bug", "Réparation programme"],
    "performance": ["Vitesse et efficacité système", "Qualité opération logicielle", "Réactivité application"],
    "autorisation": ["Autorisation accès", "Octroi droits système", "Privilège sécurité"],
    "plateforme": ["Fondation technologique", "Environnement exécution logiciel", "Base développement"],
    "plugin": ["Composant extension logicielle", "Fonctionnalité add-on programme", "Amélioration application"],
    "port": ["Point connexion réseau", "Prise interface ordinateur", "Terminaison communication"],
    "vie privée": ["Droit protection données", "Confidentialité information", "Sécurité personnelle"],
    "processus": ["Instance exécution programme", "Application en cours", "Tâche ordinateur"],
    "processeur": ["Unité calcul ordinateur", "Composant matériel CPU", "Puce traitement données"],
    "production": ["Environnement logiciel actif", "État système opérationnel", "Déploiement actif"],
    "programme": ["Application logicielle", "Instructions ordinateur", "Code exécutable"],
    "projet": ["Initiative développement", "Effort création logicielle", "Plan travail technologique"],
    "proxy": ["Système serveur intermédiaire", "Redirecteur requête réseau", "Intermédiaire connexion"],
    "cloud public": ["Services computing partagés", "Plateforme cloud multi-locataire", "Services internet disponibles"],
    "notification push": ["Alerte message application mobile", "Message utilisateur envoyé serveur", "Notification mise à jour application"],
    "mot de passe": ["Code accès sécurité", "Identifiant authentification", "Chaîne vérification utilisateur"],
    "modèle": ["Approche template conception", "Format solution récurrent", "Modèle programmation"],
    "passerelle de paiement": ["Processeur transaction en ligne", "Système paiement e-commerce", "Service transfert argent numérique"],
    "pair à pair": ["Communication directe appareils", "Modèle réseau distribué", "Interaction nœuds égaux"],
    "test de pénétration": ["Évaluation vulnérabilité sécurité", "Piratage système autorisé", "Évaluation défense cybernétique"],
    "périphérique": ["Appareil ordinateur externe", "Composant matériel supplémentaire", "Accessoire ordinateur"],
    "persistance": ["Stockage données permanent", "Rétention information", "Sauvegarde long terme"],
    "hameçonnage": ["Attaques email frauduleuses", "Tentative vol identité", "Communication en ligne trompeuse"],
    "pipeline": ["Séquence traitement données", "Étapes workflow", "Chaîne processus automatisé"],
    "pixel": ["Unité affichage écran", "Point élément image", "Composant image numérique"],
    "plateforme en tant que service": ["Plateforme application cloud", "Environnement développement PaaS", "Services plateforme en ligne"],
    "portabilité": ["Capacité transfert système", "Compatibilité multiplateforme", "Mobilité logicielle"],
    "alimentation": ["Source électricité ordinateur", "Fournisseur énergie appareil", "Unité puissance matérielle"],
    "cloud privé": ["Services cloud dédiés", "Plateforme cloud locataire unique", "Infrastructure cloud exclusive"],
    "procédure": ["Routine méthode programme", "Étapes processus logiciel", "Séquence exécution"],
    "gestion des processus": ["Contrôle exécution programme", "Administration tâches", "Gestion processus système"],
    "propriétaire de produit": ["Gestionnaire exigence développement", "Décideur fonctionnalité projet", "Rôle équipe agile"],
    "langage de programmation": ["Syntaxe développement logiciel", "Format instruction ordinateur", "Système écriture code"],

    # Q (20 termes)
    "requête": ["Demande information base données", "Question recherche", "Commande récupération données"],
    "assurance qualité": ["Processus test logiciel", "Vérification qualité", "Validation produit"],
    "informatique quantique": ["Technologie computing avancée", "Traitement physique quantique", "Calcul nouvelle génération"],
    "file d'attente": ["Structure d'attente données", "Séquence ligne processus", "Système ordonnancement tâches"],
    "code réponse rapide": ["Format code-barres matrice", "Code scannable QR", "Code information mobile"],
    "contrôle qualité": ["Vérification standard produit", "Processus maintien qualité", "Vérification conformité standard"],
    "bit quantique": ["Unité informatique quantique", "Mesure information qubit", "Représentation état quantique"],
    "langage de requête": ["Syntaxe question base données", "Format demande information", "Grammaire récupération données"],
    "optimisation de requête": ["Amélioration recherche base données", "Amélioration performance recherche", "Ajustement vitesse requête"],
    "démarrage rapide": ["Processus début rapide", "Guide initiation rapide", "Début accéléré"],

    # R (60 termes)
    "react": ["Bibliothèque interface utilisateur JavaScript", "Framework développement frontend", "Bibliothèque basée composants"],
    "design responsive": ["Mise en page web adaptative", "Compatibilité multi-appareils", "Conception interface flexible"],
    "rest": ["Architecture service web", "Transfert d'État Représentationnel", "Principe conception API"],
    "routeur": ["Directeur trafic réseau", "Gestionnaire connexion internet", "Redirecteur paquets données"],
    "runtime": ["Période exécution programme", "Temps opération logicielle", "État fonctionnement application"],
    "raspberry pi": ["Petite carte ordinateur", "Appareil computing éducatif", "Plateforme projet DIY"],
    "temps réel": ["Traitement immédiat", "Réponse système instantanée", "Gestion données en direct"],
    "récursion": ["Fonction auto-appelante", "Invocation processus répétée", "Technique répétition programmation"],
    "actualiser": ["Action mise à jour contenu", "Réaffichage écran", "Rechargement données"],
    "registre": ["Base données configuration système", "Magasin paramètres Windows", "Paramètres système d'exploitation"],
    "régression": ["Méthode analyse statistique", "Modélisation relation", "Technique apprentissage automatique"],
    "version": ["Publication version logicielle", "Déploiement produit", "Lancement application"],
    "distant": ["Capacité accès à distance", "Opération connexion réseau", "Contrôle hors site"],
    "rendu": ["Génération affichage visuel", "Processus création image", "Présentation contenu"],
    "dépôt": ["Emplacement stockage code", "Stockage contrôle version", "Archive logicielle"],
    "réinitialiser": ["Restauration système", "Retour état par défaut", "Effacement configuration"],
    "résolution": ["Niveau détail écran", "Densité pixels affichage", "Mesure clarté image"],
    "ressource": ["Actif système disponible", "Composant capacité computing", "Outil ou actif disponible"],
    "redémarrer": ["Processus redémarrage système", "Rechargement programme", "Nouveau départ"],
    "restaurer": ["Processus récupération données", "Récupération sauvegarde", "Retour système état précédent"],
    "écran retina": ["Écran haute résolution Apple", "Technologie visuelle nette", "Standard affichage Apple"],
    "rétro-ingénierie": ["Technique analyse produit", "Déconstruction système", "Examen technologie"],
    "robot": ["Système machine automatisé", "Appareil mécanique programmable", "Agent physique IA"],
    "robotique": ["Domaine technologie robot", "Ingénierie automatisation", "Science système machine"],
    "racine": ["Niveau administrateur système", "Privilège accès suprême", "Autorité superutilisateur"],
    "routeur": ["Appareil connexion réseau", "Gestionnaire trafic internet", "Centre réseau domestique"],
    "rss": ["Syndication contenu web", "Format flux actualités", "Standard distribution contenu"],
    "ruby": ["Langage de programmation", "Langage de codage dynamique", "Plateforme développement web"],
    "rust": ["Langage programmation système", "Langage sûr mémoire", "Langage performance moderne"],

    # S (80 termes)
    "sql": ["Langage de requête base données", "Langage de Requête Structuré", "Langage gestion données"],
    "serveur": ["Fournisseur service réseau", "Ordinateur offrant ressources", "Hôte données central"],
    "logiciel": ["Programmes ordinateur", "Applications numériques", "Instructions électroniques"],
    "sécurité": ["Mesures protection système", "Prévention menace cybernétique", "Sûreté information"],
    "évolutivité": ["Capacité croissance système", "Capacité expansion performance", "Capacité gestion charge"],
    "script": ["Code programme automatisation", "Programmation légère", "Fichier automatisation tâches"],
    "sdk": ["Kit de Développement Logiciel", "Collection outils programmation", "Outils construction application"],
    "moteur de recherche": ["Trouveur information web", "Localisateur contenu internet", "Système recherche en ligne"],
    "sans serveur": ["Modèle exécution cloud", "Architecture sans serveur", "Fonction en tant que Service"],
    "session": ["Période interaction utilisateur", "État connexion temporaire", "Cadre temporel activité"],
    "paramètres": ["Options configuration système", "Préférences utilisateur", "Ajustements application"],
    "partagiciel": ["Distribution logicielle essai", "Logiciel gratuit limité", "Programmes essai avant achat"],
    "shell": ["Interface commande système", "Environnement terminal", "Processeur commandes"],
    "smartphone": ["Appareil computing mobile", "Téléphone cellulaire avancé", "Ordinateur poche"],
    "médias sociaux": ["Plateformes communauté en ligne", "Sites réseautage numérique", "Réseaux sociaux internet"],
    "génie logiciel": ["Discipline programmation professionnelle", "Développement logiciel systématique", "Création d'application structurée"],
    "spam": ["Messages numériques non désirés", "Email groupé non sollicité", "Courrier électronique indésirable"],
    "tableur": ["Logiciel tableau données", "Outil analyse numérique", "Programme calcul grille"],
    "logiciel espion": ["Logiciel surveillance secret", "Collecte données covert", "Programme invasion vie privée"],
    "ssl": ["Couche de Sockets Sécurisée", "Protocole sécurité chiffrement", "Certificat sécurité web"],
    "pile": ["Combinaison technologie", "Collection couches logicielles", "Ensemble outils développement"],
    "stockage": ["Capacité rétention données", "Espace maintien information", "Mémoire numérique"],
    "streaming": ["Livraison données continue", "Lecture média temps réel", "Transfert contenu progressif"],
    "sous-réseau": ["Segment division réseau", "Sous-groupe adresse IP", "Partition réseau"],
    "superordinateur": ["Ordinateur haute performance", "Système calcul avancé", "Machine calcul scientifique"],
    "support": ["Service assistance technique", "Aide résolution problème", "Fourniture aide utilisateur"],
    "syntaxe": ["Grammaire langage programmation", "Règles structure code", "Spécification format langage"],
    "système": ["Collection technologie intégrée", "Ensemble composants coordonnés", "Configuration ordinateur organisée"],

    # T (60 termes)
    "typescript": ["JavaScript avec types", "Langage programmation Microsoft", "Sur-ensemble JS typé"],
    "tablette": ["Appareil écran tactile portable", "Plateforme computing mobile", "Ordinateur portable"],
    "balise": ["Marqueur étiquette contenu", "Catégorisation information", "Identification données"],
    "tâche": ["Unité travail computing", "Travail exécution programme", "Opération système"],
    "modèle": ["Modèle format document", "Structure design réutilisable", "Mise en page pré-faite"],
    "test": ["Processus vérification logicielle", "Méthode vérification qualité", "Procédure détection bug"],
    "thread": ["Chemin exécution programme", "Séquence traitement", "Ligne tâche concurrente"],
    "jeton": ["Objet accès sécurité", "Pièce authentification", "Unité permission numérique"],
    "outil": ["Programme utilitaire logiciel", "Application assistance développement", "Assistant technique"],
    "écran tactile": ["Interaction affichage directe", "Technologie interface tactile", "Saisie contact écran"],
    "transaction": ["Unité opération base données", "Action processus métier", "Échange données complet"],
    "transmission": ["Processus envoi données", "Transfert information", "Communication réseau"],
    "dépannage": ["Processus résolution problème", "Méthode résolution incident", "Diagnostic panne"],
    "tuple": ["Séquence données ordonnée", "Collection éléments fixe", "Structure données programmation"],
    "twitter": ["Plateforme médias sociaux", "Service microblogage", "Réseau message court"],
    "type": ["Classification catégorie données", "Genre variable programmation", "Format information"],

    # U (40 termes)
    "interface utilisateur": ["Interface Utilisateur", "Conception visuelle application", "Surface interaction utilisateur"],
    "expérience utilisateur": ["Expérience Utilisateur", "Qualité globale interaction utilisateur", "Conception interaction humain-ordinateur"],
    "ubuntu": ["Système d'exploitation Linux", "Distribution OS open-source", "Linux basé Debian"],
    "téléversement": ["Envoi données vers serveur", "Transfert fichier système distant", "Partage information vers réseau"],
    "url": ["Emplacement adresse web", "Localisateur de Ressource Uniforme", "Identifiant site internet"],
    "usb": ["Bus Série Universel", "Standard connexion appareil", "Interface périphérique ordinateur"],
    "utilisateur": ["Personne opérateur système", "Consommateur logiciel", "Utilisateur final technologie"],
    "agent utilisateur": ["Logiciel agissant pour utilisateur", "Identification navigateur", "Application cliente"],
    "histoire utilisateur": ["Description exigence développement", "Format explication fonctionnalité", "Outil développement agile"],
    "utilitaire": ["Programme assistant système", "Application outil ordinateur", "Programme assistance logicielle"],

    # V (40 termes)
    "machine virtuelle": ["Émulation ordinateur logicielle", "Environnement virtualisé", "Système d'exploitation invité"],
    "vpn": ["Réseau Privé Virtuel", "Connexion internet sécurisée", "Tunnel réseau chiffré"],
    "virus": ["Programme ordinateur malveillant", "Logiciel malveillant auto-répliquant", "Code infection numérique"],
    "réalité virtuelle": ["Environnement numérique immersif", "Monde généré ordinateur", "Expérience simulée VR"],
    "contrôle de version": ["Gestion changement code", "Suivi révision logicielle", "Système historique développement"],
    "vidéo": ["Contenu visuel mobile", "Images mobiles numériques", "Animation électronique"],
    "reconnaissance vocale": ["Technologie compréhension parole", "Traitement commande vocale", "Interprétation saisie audio"],
    "vulnérabilité": ["Point faiblesse sécurité", "Exposition défaut système", "Opportunité attaque cybernétique"],
    "validation": ["Vérification exactitude données", "Processus vérification saisie", "Confirmation précision information"],
    "variable": ["Conteneur données programmation", "Emplacement stockage valeur", "Détenteur information changeable"],

    # W (50 termes)
    "développement web": ["Processus création site web", "Construction application en ligne", "Développement logiciel internet"],
    "site web": ["Collection emplacements internet", "Groupe pages web", "Site présence en ligne"],
    "windows": ["Système d'exploitation Microsoft", "Plateforme bureau PC", "Environnement OS graphique"],
    "sans fil": ["Connexion sans câbles", "Réseautage basé radio", "Technologie sans cordon"],
    "flux de travail": ["Automatisation séquence processus", "Système procédure tâches", "Gestion processus métier"],
    "serveur web": ["Fournisseur contenu internet", "Ordinateur hébergement site web", "Système service en ligne"],
    "application web": ["Logiciel basé navigateur", "Interface programme en ligne", "Application accessible internet"],
    "wi-fi": ["Technologie réseautage sans fil", "Connexion internet radio", "Réseau local sans fil"],
    "ver": ["Logiciel malveillant auto-propagateur", "Virus se répandant réseau", "Code malveillant répliquant"],
    "conception web": ["Création visuelle site web", "Conception interface en ligne", "Mise en page page internet"],
    "hébergement web": ["Service stockage site web", "Provision contenu en ligne", "Location site internet"],
    "service web": ["Composant logiciel en ligne", "Fonction accessible internet", "Service API web"],
    "web socket": ["Communication web temps réel", "Protocole connexion persistante", "Échange données en direct"],
    "chapeau blanc": ["Pirate sécurité éthique", "Testeur pénétration autorisé", "Hacker bonne intention"],
    "widget": ["Élément composant interface", "Objet contrôle GUI", "Pièce programme visuelle"],
    "wiki": ["Plateforme site web collaborative", "Contenu modifiable communauté", "Base connaissances groupe"],
    "maquette filaire": ["Croquis mise en page interface", "Structure design basique", "Aperçu planification visuelle"],
    "station de travail": ["Système ordinateur professionnel", "Bureau haute performance", "Station computing spécialisée"],
    "world wide web": ["Système d'information global", "Réseau contenu internet", "Collection pages web"],

    # X (10 termes)
    "xml": ["Langage de Balisage Etensible", "Standard format données", "Format document structuré"],
    "xss": ["Attaque cross-site scripting", "Vulnérabilité sécurité web", "Attaque injection navigateur"],
    "xcode": ["Environnement développement Apple", "IDE programmation iOS", "Constructeur application Mac"],
    "xamarin": ["Framework mobile Microsoft", "Développement application multiplateforme", "Programmation mobile C#"],
    "xhtml": ["Version HTML étendue", "Standard HTML strict", "HTML basé XML"],

    # Y (10 termes)
    "yaml": ["Format données lisible humain", "Langage fichier configuration", "Standard sérialisation données"],
    "youtube": ["Plateforme partage vidéo", "Service vidéo en ligne", "Site vidéo Google"],

    # Z (10 termes)
    "zero day": ["Vulnérabilité logicielle inconnue", "Défaut sécurité non corrigé", "Exploit nouvellement découvert"],
    "zip": ["Format compression fichier", "Format archive données", "Format fichier compressé"],
    "zombie": ["Système ordinateur compromis", "Machine contrôlée botnet", "Appareil réseau piraté"]
}