words = {
    # A (60 términos)
    "algoritmo": ["Procedimiento paso a paso para resolver problemas", "Conjunto de reglas para cálculos", "Secuencia de instrucciones computacionales"],
    "api": ["Interfaz de Programación de Aplicaciones para comunicación de software", "Conjunto de herramientas para construir aplicaciones", "Contrato entre diferentes componentes de software"],
    "aplicación": ["Programa de software para usuarios finales", "App que realiza tareas específicas", "Programa que se ejecuta en dispositivos"],
    "autenticación": ["Proceso de verificación de identidad de usuario", "Verificación de inicio de sesión y credenciales", "Confirmación de identidad para acceder a sistemas"],
    "ia": ["Inteligencia Artificial que imita la cognición humana", "Máquinas que realizan tareas inteligentes", "Sistemas informáticos con capacidades de aprendizaje"],
    "ágil": ["Metodología de desarrollo de software iterativa", "Enfoque flexible de gestión de proyectos", "Proceso de desarrollo colaborativo"],
    "analítica": ["Análisis sistemático de datos", "Descubrimiento de patrones significativos", "Generación de insights basados en datos"],
    "android": ["Sistema operativo móvil de Google", "SO basado en Linux para smartphones", "Plataforma móvil de código abierto"],
    "arquitectura": ["Diseño estructural de sistemas", "Plan de organización de software", "Plan de estructura general del sistema"],
    "arreglo": ["Estructura de datos que almacena elementos", "Colección de elementos en programación", "Serie ordenada de valores"],
    "automatización": ["Tecnología que realiza tareas sin intervención humana", "Auto-ejecución de procesos", "Control sistemático de operaciones"],
    "aws": ["Plataforma en la nube Amazon Web Services", "Proveedor de servicios de computación en la nube", "Infraestructura en la nube de Amazon"],
    "ajax": ["JavaScript asíncrono para contenido web dinámico", "Técnica de desarrollo web", "Intercambio de datos sin recarga de página"],
    "angular": ["Framework de aplicación web de Google", "Plataforma basada en TypeScript", "Framework de desarrollo frontend"],
    "antivirus": ["Software que detecta programas maliciosos", "Sistema de protección contra malware", "Aplicación de seguridad informática"],
    "tienda de aplicaciones": ["Plataforma de distribución digital", "Mercado de aplicaciones", "Portal de descarga de software"],
    "inteligencia artificial": ["Simulación máquina de la inteligencia humana", "Sistemas informáticos con capacidades cognitivas", "Tecnología que permite comportamiento inteligente"],
    "ascii": ["Estándar de codificación de caracteres", "Código de representación de texto", "Código Estándar Americano para Intercambio de Información"],
    "activo": ["Recurso digital en desarrollo", "Archivo o componente de proyecto", "Elemento de recurso de desarrollo"],
    "archivo adjunto": ["Archivo enviado con correo electrónico", "Documento incluido con mensaje", "Inclusión de archivo en email"],
    "audio": ["Tecnología de sonido", "Procesamiento de sonido digital", "Capacidades de sonido de computadora"],
    "realidad aumentada": ["Superposición digital en el mundo real", "Tecnología de realidad mejorada", "Mejora de realidad generada por computadora"],
    "autocompletado": ["Función de predicción de texto", "Sistema de sugerencia de entrada", "Tecnología de completación de palabras"],
    "pruebas automatizadas": ["Pruebas de software sin intervención humana", "Garantía de calidad automática", "Ejecución de pruebas programática"],
    "avatar": ["Representación digital del usuario", "Representación de personaje en línea", "Imagen de identidad virtual"],
    "azure": ["Plataforma en la nube de Microsoft", "Servicio de computación en la nube", "Servicios Microsoft Azure"],

    # B (50 términos)
    "backend": ["Lado del servidor de las aplicaciones", "Operaciones de software detrás de escena", "Gestión de base de datos y servidor"],
    "ancho de banda": ["Capacidad de transferencia de datos", "Tasa de transmisión de red", "Ancho del canal de comunicación"],
    "big data": ["Conjuntos de datos extremadamente grandes", "Datos complejos que requieren procesamiento especial", "Volúmenes masivos de información"],
    "binario": ["Sistema numérico base-2", "Lenguaje informático que usa 0s y 1s", "Método de representación digital"],
    "biometría": ["Características biológicas para identificación", "Autenticación por rasgos físicos", "Tecnología de medición biológica"],
    "bit": ["Unidad más pequeña de datos digitales", "Dígito binario (0 o 1)", "Unidad básica de información informática"],
    "blockchain": ["Libro mayor digital distribuido", "Registro de transacciones descentralizado", "Cadena criptográfica de bloques"],
    "bot": ["Aplicación de software automatizada", "Programa que realiza tareas repetitivas", "Robot de internet"],
    "bootstrap": ["Framework frontend para diseño responsive", "Framework CSS para desarrollo web", "Kit de herramientas de desarrollo web de Twitter"],
    "error": ["Error o falla de software", "Error de programación", "Causa de mal funcionamiento del sistema"],
    "byte": ["Unidad de información digital", "Ocho bits de datos", "Medida de almacenamiento informático"],
    "desarrollador backend": ["Programador del lado del servidor", "Especialista en base de datos y API", "Creador de lógica del servidor"],
    "beta": ["Versión de software pre-lanzamiento", "Producto en fase de prueba", "Etapa de evaluación temprana de usuarios"],
    "navegador": ["Software de visualización de páginas web", "Aplicación de navegación por internet", "Programa de renderizado HTML"],
    "copia de seguridad": ["Copia de datos para seguridad", "Recurso de recuperación de información", "Almacenamiento duplicado para protección"],
    "procesamiento por lotes": ["Ejecución grupal de tareas", "Procesamiento de datos en masa", "Procesamiento múltiple de trabajos"],
    "pruebas beta": ["Fase de prueba de usuarios externos", "Evaluación pre-lanzamiento", "Pruebas de software en condiciones reales"],
    "archivo binario": ["Archivo informático no textual", "Formato de programa ejecutable", "Archivo legible por máquina"],
    "tasa de bits": ["Medición de velocidad de transferencia de datos", "Bits procesados por segundo", "Tasa de flujo digital"],
    "blog": ["Sitio web de diario en línea", "Publicación regular de contenido", "Plataforma de blogueo web"],
    "bluetooth": ["Tecnología inalámbrica de corto alcance", "Estándar de conectividad de dispositivos", "Protocolo de red de área personal"],
    "marcador": ["Referencia de página web guardada", "Marcador de ubicación del navegador", "Acceso rápido al sitio web"],
    "banda ancha": ["Conexión a internet de alta velocidad", "Transmisión rápida de datos", "Redes de banda ancha"],
    "búfer": ["Área de almacenamiento temporal de datos", "Área de retención de memoria", "Intermediario de transferencia de datos"],
    "reporte de error": ["Documentación de error de software", "Documento de descripción de problemas", "Reporte de seguimiento de incidencias"],

    # C (80 términos)
    "caché": ["Capa de almacenamiento de alta velocidad", "Memoria temporal para acceso rápido", "Almacenamiento de datos usados frecuentemente"],
    "nube": ["Servidores remotos de internet", "Recursos informáticos en línea", "Servicios alojados en red"],
    "código": ["Instrucciones de programación informática", "Texto fuente del software", "Instrucciones de lenguaje de programación"],
    "compilador": ["Programa que traduce código a lenguaje máquina", "Convertidor de código fuente a ejecutable", "Traductor de lenguaje de programación"],
    "cpu": ["Unidad Central de Procesamiento", "Procesador principal de la computadora", "Hardware que ejecuta instrucciones"],
    "ciberseguridad": ["Protección contra ataques digitales", "Práctica de seguridad de la información", "Defensa del sistema informático"],
    "css": ["Hojas de Estilo en Cascada para diseño web", "Lenguaje de estilo de páginas web", "Formateo de presentación HTML"],
    "criptografía": ["Técnicas de comunicación segura", "Ciencia del cifrado de información", "Métodos de protección de datos"],
    "contenedor": ["Método de empaquetado de software", "Entorno de aplicación aislado", "Unidad de despliegue Docker"],
    "cookie": ["Almacenamiento de datos de sitio web en dispositivo usuario", "Mecanismo de seguimiento del navegador", "Archivo de información de sesión"],
    "fallo": ["Falla inesperada del sistema", "Error de terminación de software", "Mal funcionamiento del programa"],
    "multiplataforma": ["Software que funciona en múltiples sistemas", "Aplicaciones compatibles con multi-OS", "Programas independientes de la plataforma"],
    "criptomoneda": ["Moneda digital cifrada", "Dinero basado en blockchain", "Activo digital descentralizado"],
    "ciberataque": ["Intrusión en sistema digital", "Violación de red informática", "Infracción de seguridad en línea"],
    "centro de datos": ["Instalación que alberga sistemas informáticos", "Ubicación de almacenamiento de servidores", "Hub de infraestructura IT"],
    "base de datos": ["Colección organizada de datos", "Almacenamiento electrónico de información", "Repositorio de datos estructurados"],
    "depuración": ["Identificación y eliminación de errores", "Corrección de problemas de software", "Proceso de solución de problemas de código"],
    "despliegue": ["Proceso de lanzamiento de software", "Instalación de aplicación", "Implementación de sistema"],
    "desarrollador": ["Creador de software", "Escritor de programas", "Constructor de aplicaciones"],
    "digital": ["Representación tecnológica electrónica", "Sistemas basados en computadora", "Tecnología no analógica"],
    "dominio": ["Cadena de identificación de red", "Nombre de dirección del sitio web", "Territorio de internet"],
    "descarga": ["Recuperación de datos desde sistema remoto", "Transferencia de archivo a dispositivo local", "Adquisición de archivo de internet"],
    "controlador": ["Software de comunicación de hardware", "Programa de control de dispositivo", "Interfaz de hardware"],
    "dinámico": ["Comportamiento cambiante o adaptativo", "Capacidad de modificación en tiempo de ejecución", "Ajuste en tiempo real"],
    "minería de datos": ["Descubrimiento de patrones en grandes conjuntos de datos", "Extracción de conocimiento de datos", "Proceso de análisis de información"],
    "ciencia de datos": ["Extracción de insights de datos", "Métodos científicos para análisis de datos", "Disciplina de estudio de información"],
    "almacén de datos": ["Repositorio central de datos", "Almacenamiento de inteligencia empresarial", "Colección de datos históricos"],
    "sistema de gestión de base de datos": ["Software para administración de base de datos", "Herramienta de gestión de almacenamiento de datos", "Software SGBD"],
    "depurador": ["Programa para encontrar errores", "Herramienta de prueba de software", "Utilidad de análisis de código"],
    "descentralizado": ["Sistema de control distribuido", "Red sin autoridad central", "Organización peer-to-peer"],
    "devops": ["Colaboración desarrollo y operaciones", "Metodología de entrega de software", "Prácticas CI/CD"],
    "transformación digital": ["Integración tecnológica en negocios", "Adopción de tecnología digital", "Modernización de procesos empresariales"],
    "sistema distribuido": ["Componentes informáticos en red", "Coordinación de múltiples computadoras", "Computación descentralizada"],
    "dns": ["Sistema de Nombres de Dominio", "Traducción de dirección de internet", "Resolución de nombre de sitio web"],
    "docker": ["Plataforma de contenedorización", "Herramienta de empaquetado de aplicaciones", "Sistema de contenedores de software"],
    "documentación": ["Escritura de instrucciones de software", "Documentos de descripción del sistema", "Materiales de referencia técnica"],
    "nombre de dominio": ["Dirección web legible por humanos", "Etiqueta de identificación del sitio web", "Nombre de ubicación de internet"],
    "notación de punto": ["Método de acceso a propiedades de objeto", "Sintaxis de programación para jerarquía", "Acceso a miembros de objeto"],
    "arrastrar y soltar": ["Método de movimiento de elementos GUI", "Interacción de interfaz visual", "Transferencia de objetos basada en mouse"],
    "actualización de controlador": ["Actualización de software de hardware", "Mejora de control de dispositivo", "Mejora de compatibilidad de hardware"],

    # D (continuación)
    "análisis de datos": ["Proceso de examen de datos", "Derivación de información", "Análisis estadístico de datos"],
    "estructura de datos": ["Formato de organización de datos", "Método de almacenamiento de información", "Disposición de datos informáticos"],
    "aprendizaje profundo": ["Redes neuronales avanzadas", "Subconjunto de aprendizaje automático", "IA con múltiples capas"],
    "aplicación de escritorio": ["Software instalado en computadora", "Programa de máquina local", "Aplicación no web"],
    "firma digital": ["Método de autenticación electrónica", "Verificación de documento digital", "Firma criptográfica"],
    "espacio en disco": ["Capacidad de almacenamiento disponible", "Espacio en disco duro", "Disponibilidad de almacenamiento informático"],
    "computación distribuida": ["Compartición de tareas multi-computadoras", "Potencia de procesamiento en red", "Operación de sistema colaborativa"],
    "programación dinámica": ["Método de optimización de algoritmo", "Técnica de resolución de problemas", "Descomposición de problema complejo"],

    # E (50 términos)
    "cifrado": ["Codificación de datos para seguridad", "Mezcla de información", "Método de protección de privacidad"],
    "ethernet": ["Estándar de conexión de red", "Tecnología de redes cableadas", "Protocolo de comunicación LAN"],
    "etl": ["Proceso Extraer Transformar Cargar", "Procedimiento de integración de datos", "Preparación de almacén de datos"],
    "comercio electrónico": ["Transacciones comerciales en línea", "Comercio electrónico", "Compras por internet"],
    "computación en el borde": ["Paradigma de computación distribuida", "Procesamiento de datos en el borde de red", "Cómputo descentralizado"],
    "elasticsearch": ["Motor de búsqueda y analítica", "Servidor de búsqueda distribuido", "Búsqueda de base de datos de documentos"],
    "correo electrónico": ["Sistema de correo electrónico", "Comunicación de mensajes digitales", "Mensajería por internet"],
    "sistema embebido": ["Computadora dentro de sistema más grande", "Dispositivo de función dedicada", "Computación de propósito especial"],
    "emoji": ["Pictograma digital", "Símbolo de emoción electrónico", "Carácter visual en mensajería"],
    "clave de cifrado": ["Código criptográfico", "Mecanismo de bloqueo de datos", "Código de acceso de seguridad"],
    "punto final": ["Punto de conexión de dispositivo", "Terminal de comunicación de red", "Dispositivo informático remoto"],
    "software empresarial": ["Aplicaciones de organización empresarial", "Programas a escala corporativa", "Sistemas de gran empresa"],
    "ethereum": ["Plataforma informática blockchain", "Criptomoneda con contratos inteligentes", "Plataforma de aplicación descentralizada"],
    "excepción": ["Manejo de errores de programa", "Anomalía en tiempo de ejecución", "Irregularidad de software"],
    "ejecutable": ["Archivo de programa ejecutable", "Archivo de aplicación de software", "Binario de programa informático"],
    "sistema experto": ["Programa de toma de decisiones IA", "Sistema basado en conocimiento", "Software de resolución de problemas"],
    "extranet": ["Extensión de red privada", "Red de socios externos", "Acceso externo controlado"],
    "aprendizaje en línea": ["Aprendizaje electrónico", "Educación en línea", "Cursos digitales"],
    "emulador": ["Imitación de hardware/software", "Programa de simulación de sistema", "Software de replicación de dispositivo"],
    "algoritmo de cifrado": ["Método de mezcla de datos", "Procedimiento criptográfico", "Proceso de codificación de seguridad"],
    "manejo de errores": ["Gestión de errores de programa", "Proceso de recuperación de excepciones", "Mecanismo de tolerancia a fallos"],
    "cable ethernet": ["Cable de conexión de red", "Enlace físico de internet", "Cable de conectividad LAN"],
    "orientado a eventos": ["Programación acción-respuesta", "Arquitectura basada en desencadenadores", "Procesamiento basado en eventos"],
    "exportación": ["Salida de datos a formato externo", "Conversión de archivo para transferencia", "Proceso de extracción de información"],
    "extensión": ["Componente add-on de software", "Mejora de funcionalidad de programa", "Plugin de navegador"],

    # F (50 términos)
    "cortafuegos": ["Sistema de seguridad de red", "Barrera de filtrado de tráfico", "Muro de protección cibernética"],
    "firmware": ["Software embebido de dispositivo", "Programa de control de hardware", "Software permanente"],
    "framework": ["Plataforma de desarrollo de software", "Fundación de estructura de aplicación", "Kit de herramientas de programación"],
    "frontend": ["Desarrollo de interfaz de usuario", "Programación del lado del cliente", "Parte visual de aplicación"],
    "full stack": ["Desarrollo frontend y backend", "Programación de extremo a extremo", "Desarrollo de aplicación completo"],
    "función": ["Rutina de programación", "Bloque de código reutilizable", "Procedimiento de software"],
    "programación funcional": ["Paradigma de programación usando funciones", "Estilo de codificación declarativo", "Codificación basada en funciones matemáticas"],
    "lógica difusa": ["Sistema lógico multi-valorado", "Método de razonamiento aproximado", "Toma de decisiones no binaria"],
    "sistema de archivos": ["Organización de almacenamiento de datos", "Estructura de gestión de archivos", "Método de organización de almacenamiento"],
    "filtro": ["Mecanismo de selección de datos", "Proceso de cribado de información", "Herramienta de separación de contenido"],
    "firefox": ["Navegador web Mozilla", "Navegador de código abierto", "Software de navegación por internet"],
    "flask": ["Framework web de Python", "Herramienta de micro aplicación web", "Desarrollo web ligero"],
    "flutter": ["Kit de interfaz de usuario de Google", "Framework de aplicación multiplataforma", "SDK de desarrollo móvil"],
    "foro": ["Plataforma de discusión en línea", "Tablero de mensajes comunitario", "Espacio de conversación digital"],
    "fps": ["Cuadros por segundo", "Medida de suavidad de animación", "Métrica de rendimiento de video"],
    "freeware": ["Distribución de software gratuito", "Aplicaciones sin costo", "Programas gratis"],
    "ftp": ["Protocolo de Transferencia de Archivos", "Intercambio de archivos en red", "Método de transmisión de datos"],
    "búsqueda de texto completo": ["Búsqueda de contenido de documento", "Examen completo de texto", "Recuperación textual integral"],
    "pruebas funcionales": ["Verificación de características de software", "Prueba de requisitos del sistema", "Verificación de comportamiento de aplicación"],
    "a prueba de futuro": ["Viabilidad tecnológica a largo plazo", "Diseño de compatibilidad futura", "Planificación tecnológica sostenible"],

    # G (40 términos)
    "git": ["Sistema de control de versiones", "Seguimiento de cambios de código", "Gestión de código fuente"],
    "github": ["Plataforma de alojamiento de código", "Servicio de repositorio Git", "Sitio de colaboración de desarrolladores"],
    "gpu": ["Unidad de Procesamiento Gráfico", "Procesador de computación visual", "Hardware de computación paralela"],
    "interfaz gráfica de usuario": ["Interfaz Gráfica de Usuario", "Interacción visual con computadora", "Interfaz de apuntar y hacer clic"],
    "google cloud": ["Plataforma en la nube de Google", "Servicios de computación en la nube GCP", "Servicios de infraestructura de Google"],
    "graphql": ["Lenguaje de consulta API", "Especificación de obtención de datos", "Solicitudes de datos en tiempo de ejecución"],
    "juegos": ["Industria de videojuegos", "Entretenimiento interactivo", "Gameplay digital"],
    "puerta de enlace": ["Punto de conexión de red", "Dispositivo de traducción de protocolo", "Nodo de acceso de red"],
    "geolocalización": ["Identificación de posición geográfica", "Tecnología de detección de ubicación", "Servicios de posicionamiento"],
    "gitlab": ["Plataforma DevOps", "Administrador de repositorio de código", "Herramienta de ciclo de vida desarrollo software"],
    "golang": ["Lenguaje de programación de Google", "Desarrollo de lenguaje Go", "Lenguaje de programación de sistemas"],
    "google analytics": ["Análisis de tráfico web", "Seguimiento de rendimiento de sitio web", "Servicio de analítica digital"],
    "descenso de gradiente": ["Optimización de aprendizaje automático", "Método de entrenamiento de algoritmo", "Ajuste de parámetros de modelo"],
    "base de datos de grafos": ["Almacenamiento de datos centrado en relaciones", "Base de datos de estructura de red", "Modelo de datos nodo-conexión"],
    "computación en grid": ["Arquitectura de computación distribuida", "Compartición de recursos de red", "Sistema de procesamiento paralelo"],
    "gsm": ["Sistema Global para Comunicaciones Móviles", "Estándar de red móvil", "Tecnología celular"],
    "pruebas de interfaz gráfica": ["Verificación de interfaz de usuario", "Pruebas de componentes visuales", "Verificación de funcionalidad de interfaz"],
    "gzip": ["Formato de compresión de archivos", "Reducción de tamaño de datos", "Algoritmo de compresión"],
    "desarrollo de juegos": ["Creación de videojuegos", "Producción de software interactivo", "Programación de entretenimiento"],
    "ia general": ["Inteligencia artificial a nivel humano", "Capacidad integral de IA", "Inteligencia de máquina cognitiva completa"],

    # H (40 términos)
    "html": ["Lenguaje de Marcado de Hipertexto", "Lenguaje de estructura de página web", "Marcado de contenido de sitio web"],
    "http": ["Protocolo de Transferencia de Hipertexto", "Comunicación de datos web", "Intercambio de información por internet"],
    "https": ["Protocolo web seguro", "HTTP cifrado", "Comunicación por internet protegida"],
    "hadoop": ["Framework de procesamiento de big data", "Plataforma de computación distribuida", "Gestión de grandes conjuntos de datos"],
    "hardware": ["Componentes físicos de computadora", "Dispositivos tecnológicos tangibles", "Equipos informáticos"],
    "hash": ["Función de huella digital de datos", "Resumen criptográfico", "Generación de valor único"],
    "hashing": ["Proceso de transformación de datos", "Creación de valor de tamaño fijo", "Huella digital numérica"],
    "alojamiento": ["Servicio de almacenamiento de sitio web", "Provisión de servidor", "Hospedaje de contenido en línea"],
    "aplicación híbrida": ["Aplicación mixta nativa-web", "Aplicación móvil multiplataforma", "Software multi-entorno"],
    "hipervisor": ["Administrador de máquina virtual", "Virtualización de hardware", "Programa de control VM"],
    "hackathon": ["Evento de competencia de codificación", "Maratón de programación", "Concurso de desarrollo de software"],
    "disco duro": ["Dispositivo de almacenamiento de datos informático", "Hardware de almacenamiento magnético", "Almacenamiento de datos permanente"],
    "encabezado": ["Sección de metadatos de documento", "Información de paquete de datos", "Parte inicial de mensaje"],
    "mapa de calor": ["Técnica de visualización de datos", "Visualización de información codificada por color", "Mapeo de intensidad"],
    "hexadecimal": ["Sistema numérico base-16", "Representación numérica de 16 dígitos", "Formato numérico de programación"],
    "página de inicio": ["Página principal del sitio web", "Punto de entrada del sitio", "Ubicación web primaria"],
    "host": ["Proveedor de servicio de red", "Computadora que ofrece servicios", "Sistema que ejecuta aplicaciones"],
    "parche crítico": ["Parche de software urgente", "Reparación de error de emergencia", "Actualización crítica"],
    "html5": ["Estándar web moderno", "Versión HTML avanzada", "Marcado web actual"],
    "http2": ["Actualización de protocolo web", "Versión HTTP más rápida", "Comunicación web mejorada"],

    # I (60 términos)
    "iot": ["Internet de las Cosas", "Dispositivos físicos en red", "Objetos conectados inteligentes"],
    "dirección ip": ["Dirección de Protocolo de Internet", "Identificador de dispositivo de red", "Etiqueta de ubicación digital"],
    "ide": ["Entorno de Desarrollo Integrado", "Suite de software de programación", "Plataforma de edición de código"],
    "ios": ["Sistema operativo móvil de Apple", "Plataforma iPhone/iPad", "SO de dispositivo Apple"],
    "ipv6": ["Protocolo de Internet versión 6", "Direccionamiento IP moderno", "Direcciones de internet expandidas"],
    "iteración": ["Ciclo de proceso repetido", "Repetición de desarrollo", "Mejora secuencial"],
    "integración": ["Proceso de combinación de sistemas", "Conexión de componentes", "Unificación de software"],
    "interfaz": ["Punto de interacción del sistema", "Límite de conexión", "Superficie de comunicación"],
    "internet": ["Red informática global", "Sistema web mundial", "Red de información digital"],
    "intranet": ["Red organizacional privada", "Red interna de empresa", "Red local restringida"],
    "dispositivo iot": ["Objeto físico conectado a internet", "Dispositivo en red inteligente", "Cosa habilitada para web"],
    "cámara ip": ["Cámara de Protocolo de Internet", "Cámara conectada en red", "Vigilancia basada en web"],
    "isp": ["Proveedor de Servicios de Internet", "Empresa de acceso a internet", "Servicio de conectividad web"],
    "tecnologías de la información": ["Tecnologías de la Información", "Campo de sistemas informáticos", "Sector de tecnología digital"],
    "procesamiento de imágenes": ["Manipulación de imagen digital", "Preparación de visión por computadora", "Análisis gráfico"],
    "base de datos en memoria": ["Almacenamiento de datos en RAM", "Base de datos residente en memoria", "Sistema de datos de acceso rápido"],
    "indexación": ["Organización de datos para búsqueda", "Catalogación de información", "Preparación de recuperación rápida"],
    "infraestructura": ["Fundación tecnológica", "Estructura subyacente del sistema", "Base operativa de TI"],
    "mensajería instantánea": ["Comunicación de texto en tiempo real", "Tecnología de chat en vivo", "Intercambio de mensajes inmediato"],
    "internet explorer": ["Navegador web de Microsoft", "Aplicación de navegador heredada", "Navegador predeterminado de Windows"],
    "interoperabilidad": ["Capacidad de cooperación del sistema", "Compatibilidad multiplataforma", "Capacidad de integración tecnológica"],
    "detección de intrusiones": ["Monitoreo de violación de seguridad", "Detección de acceso no autorizado", "Sistema de protección de red"],
    "telefonía ip": ["Llamadas telefónicas por protocolo internet", "Comunicación de voz digital", "Telefonía basada en red"],
    "ipv4": ["Protocolo de Internet original", "Direccionamiento IP tradicional", "Protocolo de internet heredado"],
    "soporte técnico": ["Servicio de asistencia tecnológica", "Servicios de ayuda informática", "Resolución de problemas técnicos"],

    # J (30 términos)
    "java": ["Plataforma de lenguaje de programación", "Lenguaje orientado a objetos", "Escribir una vez ejecutar en cualquier lugar"],
    "javascript": ["Lenguaje de scripting web", "Programación del lado del cliente", "Lenguaje de interacción del navegador"],
    "json": ["Notación de Objetos de JavaScript", "Formato de intercambio de datos", "Estructura de datos ligera"],
    "jquery": ["Biblioteca de JavaScript", "Herramienta de manipulación DOM", "Framework de desarrollo web"],
    "jvm": ["Máquina Virtual de Java", "Entorno de ejecución de Java", "Plataforma de ejecución de bytecode"],
    "jdbc": ["Conectividad de Java con Bases de Datos", "API de conexión a base de datos", "Acceso a datos de Java"],
    "jupyter": ["Plataforma de computación interactiva", "Cuaderno de ciencia de datos", "Herramienta de documentación de código"],
    "programador de tareas": ["Sistema de automatización de tareas", "Controlador de tiempo de procesos", "Administrador de carga de trabajo"],
    "unión": ["Combinación de tablas de base de datos", "Fusión de datos SQL", "Conexión relacional"],
    "jailbreak": ["Eliminación de restricciones iOS", "Desbloqueo de dispositivo Apple", "Modificación de SO móvil"],
    "jar": ["Archivo Java Archive", "Formato de paquete Java", "Paquete Java ejecutable"],
    "java ee": ["Edición Empresarial de Java", "Plataforma Java a gran escala", "Framework de aplicación empresarial"],
    "framework javascript": ["Estructura de desarrollo JS", "Kit de herramientas de aplicación web", "Plataforma de programación del lado cliente"],
    "jit": ["Compilación Justo a Tiempo", "Optimización de código en tiempo de ejecución", "Compilación dinámica"],
    "trabajo": ["Tarea informática programada", "Proceso en segundo plano", "Unidad de trabajo automatizada"],

    # K (30 términos)
    "kernel": ["Núcleo del sistema operativo", "Administrador de recursos del sistema", "Control central de computadora"],
    "clave": ["Identificador de base de datos", "Código criptográfico", "Referencia de datos única"],
    "teclado": ["Dispositivo de entrada de computadora", "Hardware de escritura", "Herramienta de entrada de caracteres"],
    "fotograma clave": ["Punto de referencia de animación", "Fotograma de definición de movimiento", "Marcador de línea de tiempo"],
    "palabra clave": ["Identificador de término de búsqueda", "Palabra reservada de programación", "Término de clasificación de contenido"],
    "terminar": ["Terminación de proceso", "Comando de detener programa", "Finalización de tarea"],
    "base de conocimientos": ["Repositorio de información", "Colección organizada de datos", "Base de datos de referencia"],
    "kubernetes": ["Sistema de orquestación de contenedores", "Plataforma de gestión Docker", "Automatización de despliegue en nube"],
    "kvm": ["Conmutador de Teclado Video Mouse", "Control de múltiples computadoras", "Dispositivo de compartición de hardware"],
    "par clave-valor": ["Formato de almacenamiento de datos", "Estructura simple de base de datos", "Combinación atributo-valor"],
    "keylogger": ["Software de registro de pulsaciones", "Programa de monitoreo de entrada", "Rastreador de actividad de escritura"],
    "kilobyte": ["Unidad de almacenamiento digital", "Medida de tamaño de archivo", "Medida de cantidad de datos"],
    "kiosco": ["Terminal de información interactivo", "Estación de autoservicio", "Computadora de acceso público"],
    "grafo de conocimiento": ["Estructura de red de información", "Representación semántica de datos", "Mapa de relaciones de entidades"],
    "kpi": ["Indicador Clave de Rendimiento", "Métrica de medición de éxito", "Métrica empresarial"],

    # L (50 términos)
    "linux": ["Sistema operativo de código abierto", "Kernel de tipo Unix", "Plataforma de software libre"],
    "laravel": ["Framework web de PHP", "Plataforma de desarrollo MVC", "Framework PHP moderno"],
    "balanceo de carga": ["Método de distribución de tráfico", "Compartición de carga de servidor", "Optimización de rendimiento"],
    "biblioteca": ["Colección de código para reutilización", "Paquete de recursos de programación", "Archivo de componentes de software"],
    "bucle": ["Estructura de repetición de programación", "Mecanismo de iteración de código", "Bloque de ejecución repetida"],
    "latencia": ["Tiempo de retardo de red", "Desfase de transferencia de datos", "Medición de tiempo de respuesta"],
    "almacenamiento local": ["Almacenamiento de datos del navegador", "Guardado de datos del lado cliente", "API de almacenamiento web"],
    "registro": ["Grabación de actividad del sistema", "Proceso de seguimiento de eventos", "Monitoreo de aplicación"],
    "aprendizaje automático": ["Reconocimiento de patrones IA", "Aprendizaje algorítmico de datos", "Entrenamiento de modelo predictivo"],
    "microservicios": ["Arquitectura de aplicación modular", "Componentes de servicio independientes", "Diseño de sistema distribuido"],
    "aplicación móvil": ["Aplicación de smartphone", "Software de dispositivo móvil", "Aplicación portátil"],
    "mantenimiento": ["Actividades de conservación del sistema", "Proceso de actualización de software", "Cuidado de tecnología"],
    "malware": ["Programas de software malicioso", "Código informático dañino", "Software de amenaza digital"],
    "metadatos": ["Datos sobre datos", "Descripción de información", "Atributos de contenido"],
    "middleware": ["Capa de conexión de software", "Herramienta de integración de aplicaciones", "Software puente de sistema"],

    # M (70 términos)
    "aprendizaje automático": ["Reconocimiento de patrones IA", "Aprendizaje algorítmico de datos", "Entrenamiento de modelo predictivo"],
    "microservicios": ["Arquitectura de aplicación modular", "Componentes de servicio independientes", "Diseño de sistema distribuido"],
    "aplicación móvil": ["Aplicación de smartphone", "Software de dispositivo móvil", "Aplicación portátil"],
    "mantenimiento": ["Actividades de conservación del sistema", "Proceso de actualización de software", "Cuidado de tecnología"],
    "malware": ["Programas de software malicioso", "Código informático dañino", "Software de amenaza digital"],
    "metadatos": ["Datos sobre datos", "Descripción de información", "Atributos de contenido"],
    "middleware": ["Capa de conexión de software", "Herramienta de integración de aplicaciones", "Software puente de sistema"],
    "migración": ["Proceso de transferencia de sistema", "Procedimiento de movimiento de datos", "Transición de plataforma"],
    "mobile first": ["Prioridad de diseño móvil", "Desarrollo enfocado en smartphone", "Enfoque de diseño responsive"],
    "módem": ["Dispositivo de conexión a internet", "Convertidor de señal de red", "Hardware de comunicación digital"],
    "módulo": ["Unidad de componente de software", "Sección de programa", "Paquete de código"],
    "monitoreo": ["Proceso de observación del sistema", "Seguimiento de rendimiento", "Observación de aplicación"],
    "multihilo": ["Ejecución de tareas paralelas", "Procesamiento simultáneo", "Programación concurrente"],
    "mvc": ["Arquitectura Modelo Vista Controlador", "Patrón de diseño de software", "Patrón de separación de concerns"],
    "mysql": ["Sistema de base de datos relacional", "Base de datos de código abierto", "Gestión de base de datos SQL"],
    "dirección mac": ["Identificador de hardware", "Dirección de interfaz de red", "Dirección física de dispositivo"],
    "código máquina": ["Lenguaje nativo de computadora", "Instrucciones binarias", "Comandos directos de procesador"],
    "mainframe": ["Sistema de computadora grande", "Plataforma informática empresarial", "Servidor de alto rendimiento"],
    "análisis de malware": ["Examen de software de amenaza", "Investigación de virus", "Revisión de código de seguridad"],
    "mercado": ["Plataforma de producto digital", "Tienda en línea de aplicaciones", "Centro de distribución de software"],
    "memoria": ["Almacenamiento de datos de computadora", "Espacio de trabajo RAM", "Mantenimiento de información temporal"],
    "microprocesador": ["Chip de procesador de computadora", "Circuito integrado CPU", "Unidad central de procesamiento"],
    "dispositivo móvil": ["Equipo informático portátil", "Smartphone o tableta", "Tecnología de mano"],
    "modelo": ["Estructura de representación de datos", "Simulación de sistema", "Marco conceptual"],
    "modulación": ["Proceso de conversión de señal", "Método de transmisión de datos", "Alteración de onda"],
    "monitor": ["Pantalla de visualización de computadora", "Rastreador de rendimiento del sistema", "Herramienta de observación"],
    "placa base": ["Placa de circuito principal de computadora", "Conector de componentes del sistema", "Placa central de computadora"],
    "ratón": ["Dispositivo de apuntamiento de computadora", "Hardware de control de cursor", "Herramienta de navegación de entrada"],
    "multimedia": ["Contenido múltiple de medios", "Materiales de audio-video", "Combinación de contenido digital"],
    "multitarea": ["Manejo de múltiples trabajos", "Ejecución de tareas simultáneas", "Operación paralela"],

    # N (40 términos)
    "red neuronal": ["Simulación de cerebro IA", "Modelo de aprendizaje automático", "Sistema de reconocimiento de patrones"],
    "nodo": ["Punto de conexión de red", "Entorno de ejecución JavaScript", "Componente del sistema"],
    "npm": ["Gestor de Paquetes de Node", "Repositorio de biblioteca JavaScript", "Sistema de paquetes de código"],
    "red": ["Sistema de conexión de computadoras", "Infraestructura de comunicación", "Interconexión de dispositivos"],
    "nosql": ["Base de datos no relacional", "Almacenamiento de datos flexible", "Enfoque moderno de base de datos"],
    "aplicación nativa": ["Aplicación específica de plataforma", "Software optimizado para SO", "Programa nativo de dispositivo"],
    "navegación": ["Sistema de movimiento de interfaz", "Guía de recorrido de usuario", "Diseño de estructura de menú"],
    "networking": ["Práctica de conexión de computadoras", "Configuración de comunicación de dispositivos", "Establecimiento de red"],
    "normalización": ["Proceso de organización de base de datos", "Optimización de estructura de datos", "Estandarización de información"],
    "notificación": ["Mensaje de alerta del sistema", "Actualización de información de usuario", "Mensaje de aplicación"],
    "nulo": ["Representación de valor vacío", "Indicador de sin datos", "Marcador de información faltante"],
    "espacio de nombres": ["Contenedor de organización de código", "Alcance de contexto de nombres", "Espacio de identificador de programación"],
    "procesamiento de lenguaje natural": ["Comprensión de lenguaje humano por computadora", "Tecnología de análisis de texto", "Capacidad lingüística de IA"],
    "comunicación de campo cercano": ["Tecnología inalámbrica de corto alcance", "Intercambio de datos sin contacto", "Comunicación de proximidad NFC"],
    "seguridad de red": ["Medidas de protección de conexión", "Sistemas de defensa cibernética", "Prevención de amenazas de red"],
    "node js": ["Plataforma de tiempo de ejecución JavaScript", "JavaScript del lado del servidor", "Entorno de programación asíncrona"],
    "base de datos nosql": ["Almacenamiento de datos no tabular", "Base de datos de esquema flexible", "Gestión de datos moderna"],
    "sistema de notificaciones": ["Mecanismo de distribución de alertas", "Plataforma de entrega de mensajes", "Servicio de actualización de usuario"],

    # O (40 términos)
    "código abierto": ["Código disponible públicamente", "Software desarrollado por comunidad", "Programación de acceso libre"],
    "sistema operativo": ["Software de gestión de computadora", "Plataforma de operación de dispositivo", "Administrador de recursos del sistema"],
    "optimización": ["Proceso de mejora de rendimiento", "Aumento de eficiencia", "Ajuste del sistema"],
    "oracle": ["Empresa de base de datos y productos", "Proveedor de software empresarial", "Sistema de base de datos relacional"],
    "salida": ["Datos de resultado del sistema", "Entrega de información procesada", "Producción de programa"],
    "objeto": ["Entidad de datos de programación", "Instancia de código con propiedades", "Unidad fundamental de POO"],
    "programación orientada a objetos": ["Metodología de organización de código", "Desarrollo basado en objetos", "Paradigma de software POO"],
    "sin conexión": ["Modo de operación desconectado", "Estado sin acceso a internet", "Funcionalidad solo local"],
    "en línea": ["Estado conectado a internet", "Disponibilidad de red", "Modo de acceso web"],
    "api abierta": ["Interfaz de programación pública", "Conexión de software accesible", "Punto de integración disponible"],
    "tecnología operativa": ["Sistemas de control industrial", "Gestión de dispositivos físicos", "Infraestructura OT"],
    "fibra óptica": ["Transmisión de datos basada en luz", "Cable de red de alta velocidad", "Tecnología de fibra óptica"],
    "optimizador": ["Herramienta de mejora de rendimiento", "Software de aumento de eficiencia", "Programa de ajuste del sistema"],
    "orquestación": ["Gestión automatizada de flujo de trabajo", "Sistema de coordinación de procesos", "Disposición de servicios"],
    "búsqueda orgánica": ["Resultados de búsqueda naturales", "Hallazgos web no pagados", "Resultados de búsqueda algorítmica"],
    "dispositivo de salida": ["Hardware de presentación de información", "Equipo de visualización de resultados", "Herramienta de presentación de datos"],
    "desbordamiento": ["Capacidad de datos excedida", "Límite de almacenamiento superado", "Error de búfer excedido"],

    # P (80 términos)
    "python": ["Lenguaje de programación", "Lenguaje de codificación de alto nivel", "Herramienta de desarrollo versátil"],
    "programación": ["Proceso de creación de software", "Actividad de escritura de código", "Desarrollo de instrucciones de computadora"],
    "protocolo": ["Estándar de comunicación", "Reglas de intercambio de datos", "Especificación de interacción de red"],
    "php": ["Lenguaje de desarrollo web", "Scripting del lado del servidor", "Programación de sitio web dinámico"],
    "paquete": ["Unidad de distribución de software", "Paquete de código", "Colección de programas"],
    "parche": ["Actualización de corrección de software", "Lanzamiento de corrección de errores", "Reparación de programa"],
    "rendimiento": ["Velocidad y eficiencia del sistema", "Calidad de operación del software", "Capacidad de respuesta de aplicación"],
    "permiso": ["Autorización de acceso", "Concesión de derechos del sistema", "Privilegio de seguridad"],
    "plataforma": ["Fundación tecnológica", "Entorno de ejecución de software", "Base de desarrollo"],
    "plugin": ["Componente de extensión de software", "Característica add-on de programa", "Mejora de aplicación"],
    "puerto": ["Punto de conexión de red", "Enchufe de interfaz de computadora", "Endpoint de comunicación"],
    "privacidad": ["Derecho de protección de datos", "Confidencialidad de información", "Seguridad personal"],
    "proceso": ["Instancia de ejecución de programa", "Aplicación en ejecución", "Tarea de computadora"],
    "procesador": ["Unidad de cálculo de computadora", "Componente de hardware CPU", "Chip de procesamiento de datos"],
    "producción": ["Entorno de software en vivo", "Estado operativo del sistema", "Despliegue activo"],
    "programa": ["Aplicación de software", "Instrucciones de computadora", "Código ejecutable"],
    "proyecto": ["Iniciativa de desarrollo", "Esfuerzo de creación de software", "Plan de trabajo tecnológico"],
    "proxy": ["Sistema de servidor intermediario", "Reenviador de solicitud de red", "Intermediario de conexión"],
    "nube pública": ["Servicios de computación compartidos", "Plataforma en la nube multiinquilino", "Servicios de internet disponibles"],
    "notificación push": ["Alerta de mensaje de aplicación móvil", "Mensaje de usuario enviado por servidor", "Notificación de actualización de aplicación"],
    "contraseña": ["Código de acceso de seguridad", "Credencial de autenticación", "Cadena de verificación de usuario"],
    "patrón": ["Enfoque de plantilla de diseño", "Formato de solución recurrente", "Modelo de programación"],
    "pasarela de pago": ["Procesador de transacciones en línea", "Sistema de pago de comercio electrónico", "Servicio de transferencia de dinero digital"],
    "peer to peer": ["Comunicación directa de dispositivos", "Modelo de red distribuida", "Interacción de nodos iguales"],
    "pruebas de penetración": ["Evaluación de vulnerabilidad de seguridad", "Pirateo autorizado del sistema", "Evaluación de defensa cibernética"],
    "periférico": ["Dispositivo externo de computadora", "Componente de hardware adicional", "Accesorio de computadora"],
    "persistencia": ["Almacenamiento permanente de datos", "Retención de información", "Guardado a largo plazo"],
    "phishing": ["Ataques de correo electrónico fraudulentos", "Intento de robo de identidad", "Comunicación en línea engañosa"],
    "pipeline": ["Secuencia de procesamiento de datos", "Etapas de flujo de trabajo", "Cadena de procesos automatizados"],
    "píxel": ["Unidad de pantalla de visualización", "Punto de elemento de imagen", "Componente de imagen digital"],
    "plataforma como servicio": ["Plataforma de aplicación en la nube", "Entorno de desarrollo PaaS", "Servicios de plataforma en línea"],
    "portabilidad": ["Capacidad de transferencia del sistema", "Compatibilidad multiplataforma", "Movilidad de software"],
    "fuente de alimentación": ["Fuente de electricidad de computadora", "Proveedor de energía de dispositivo", "Unidad de potencia de hardware"],
    "nube privada": ["Servicios en la nube dedicados", "Plataforma en la nube de inquilino único", "Infraestructura en la nube exclusiva"],
    "procedimiento": ["Rutina de método de programa", "Pasos de proceso de software", "Secuencia de ejecución"],
    "gestión de procesos": ["Control de ejecución de programa", "Administración de tareas", "Manejo de procesos del sistema"],
    "propietario del producto": ["Gerente de requisitos de desarrollo", "Tomador de decisiones de características del proyecto", "Rol de equipo ágil"],
    "lenguaje de programación": ["Sintaxis de desarrollo de software", "Formato de instrucción de computadora", "Sistema de escritura de código"],

    # Q (20 términos)
    "consulta": ["Solicitud de información de base de datos", "Pregunta de búsqueda", "Comando de recuperación de datos"],
    "garantía de calidad": ["Proceso de prueba de software", "Verificación de calidad", "Validación de producto"],
    "computación cuántica": ["Tecnología de computación avanzada", "Procesamiento de física cuántica", "Cómputo de próxima generación"],
    "cola": ["Estructura de espera de datos", "Secuencia de línea de proceso", "Sistema de ordenación de tareas"],
    "código de respuesta rápida": ["Formato de código de barras matricial", "Código QR escaneable", "Código de información móvil"],
    "control de calidad": ["Verificación de estándar de producto", "Proceso de mantenimiento de calidad", "Verificación de cumplimiento de estándar"],
    "bit cuántico": ["Unidad de computación cuántica", "Medida de información qubit", "Representación de estado cuántico"],
    "lenguaje de consulta": ["Sintaxis de pregunta de base de datos", "Formato de solicitud de información", "Gramática de recuperación de datos"],
    "optimización de consultas": ["Mejora de búsqueda de base de datos", "Mejora de rendimiento de búsqueda", "Ajuste de velocidad de consulta"],
    "inicio rápido": ["Proceso de inicio rápido", "Guía de iniciación rápida", "Comienzo acelerado"],

    # R (60 términos)
    "react": ["Biblioteca de interfaz de usuario JavaScript", "Framework de desarrollo frontend", "Biblioteca basada en componentes"],
    "diseño responsive": ["Diseño web adaptable", "Compatibilidad multi-dispositivos", "Diseño de interfaz flexible"],
    "rest": ["Arquitectura de servicio web", "Transferencia de Estado Representacional", "Principio de diseño API"],
    "enrutador": ["Director de tráfico de red", "Administrador de conexión a internet", "Reenviador de paquetes de datos"],
    "tiempo de ejecución": ["Período de ejecución de programa", "Tiempo de operación de software", "Estado de ejecución de aplicación"],
    "raspberry pi": ["Pequeña placa de computadora", "Dispositivo informático educativo", "Plataforma de proyectos DIY"],
    "tiempo real": ["Procesamiento inmediato", "Respuesta instantánea del sistema", "Manejo de datos en vivo"],
    "recursión": ["Función de auto-llamada", "Invocación de proceso repetida", "Técnica de repetición de programación"],
    "actualizar": ["Acción de actualización de contenido", "Redisplay de pantalla", "Recarga de datos"],
    "registro": ["Base de datos de configuración del sistema", "Almacén de configuraciones de Windows", "Configuraciones del sistema operativo"],
    "regresión": ["Método de análisis estadístico", "Modelado de relaciones", "Técnica de aprendizaje automático"],
    "lanzamiento": ["Publicación de versión de software", "Despliegue de producto", "Lanzamiento de aplicación"],
    "remoto": ["Capacidad de acceso a distancia", "Operación de conexión de red", "Control fuera del sitio"],
    "renderizado": ["Generación de visualización", "Proceso de creación de imagen", "Presentación de contenido"],
    "repositorio": ["Ubicación de almacenamiento de código", "Almacenamiento de control de versiones", "Archivo de software"],
    "reiniciar": ["Proceso de reinicio del sistema", "Recarga de programa", "Nuevo inicio"],
    "restaurar": ["Proceso de recuperación de datos", "Recuperación de copia de seguridad", "Retorno del sistema a estado anterior"],
    "pantalla retina": ["Pantalla de alta resolución de Apple", "Tecnología visual nítida", "Estándar de visualización de Apple"],
    "ingeniería inversa": ["Técnica de análisis de producto", "Deconstrucción de sistema", "Examen de tecnología"],
    "robot": ["Sistema de máquina automatizada", "Dispositivo mecánico programable", "Agente físico de IA"],
    "robótica": ["Campo de tecnología de robots", "Ingeniería de automatización", "Ciencia de sistemas de máquinas"],
    "raíz": ["Nivel de administrador del sistema", "Privilegio de acceso más alto", "Autoridad de superusuario"],
    "enrutador": ["Dispositivo de conexión de red", "Administrador de tráfico de internet", "Centro de red doméstica"],
    "rss": ["Sindicación de contenido web", "Formato de fuente de noticias", "Estándar de distribución de contenido"],
    "ruby": ["Lenguaje de programación", "Lenguaje de codificación dinámico", "Plataforma de desarrollo web"],
    "rust": ["Lenguaje de programación de sistemas", "Lenguaje seguro para memoria", "Lenguaje de rendimiento moderno"],

    # S (80 términos)
    "sql": ["Lenguaje de consulta de base de datos", "Lenguaje de Consulta Estructurado", "Lenguaje de gestión de datos"],
    "servidor": ["Proveedor de servicio de red", "Computadora que ofrece recursos", "Host central de datos"],
    "software": ["Programas de computadora", "Aplicaciones digitales", "Instrucciones electrónicas"],
    "seguridad": ["Medidas de protección del sistema", "Prevención de amenazas cibernéticas", "Seguridad de la información"],
    "escalabilidad": ["Capacidad de crecimiento del sistema", "Capacidad de expansión de rendimiento", "Capacidad de manejo de carga"],
    "script": ["Código de programa de automatización", "Programación ligera", "Archivo de automatización de tareas"],
    "sdk": ["Kit de Desarrollo de Software", "Colección de herramientas de programación", "Herramientas de construcción de aplicaciones"],
    "motor de búsqueda": ["Buscador de información web", "Localizador de contenido de internet", "Sistema de búsqueda en línea"],
    "sin servidor": ["Modelo de ejecución en la nube", "Arquitectura sin servidor", "Función como Servicio"],
    "sesión": ["Período de interacción del usuario", "Estado de conexión temporal", "Marco temporal de actividad"],
    "configuración": ["Opciones de configuración del sistema", "Preferencias del usuario", "Ajustes de aplicación"],
    "shareware": ["Distribución de software de prueba", "Software gratuito limitado", "Programas de prueba antes de comprar"],
    "shell": ["Interfaz de comandos del sistema", "Entorno de terminal", "Procesador de comandos"],
    "smartphone": ["Dispositivo informático móvil", "Teléfono celular avanzado", "Computadora de bolsillo"],
    "redes sociales": ["Plataformas de comunidad en línea", "Sitios de redes digitales", "Redes sociales de internet"],
    "ingeniería de software": ["Disciplina de programación profesional", "Desarrollo sistemático de software", "Creación de aplicación estructurada"],
    "spam": ["Mensajes digitales no deseados", "Correo electrónico masivo no solicitado", "Correo basura electrónico"],
    "hoja de cálculo": ["Software de tabla de datos", "Herramienta de análisis numérico", "Programa de cálculo de cuadrícula"],
    "spyware": ["Software de monitoreo secreto", "Recolección de datos encubierta", "Programa de invasión de privacidad"],
    "ssl": ["Capa de Socket Seguro", "Protocolo de seguridad de cifrado", "Certificado de seguridad web"],
    "pila": ["Combinación de tecnología", "Colección de capas de software", "Conjunto de herramientas de desarrollo"],
    "almacenamiento": ["Capacidad de retención de datos", "Espacio de mantenimiento de información", "Memoria digital"],
    "streaming": ["Entrega continua de datos", "Reproducción de medios en tiempo real", "Transferencia de contenido progresivo"],
    "subred": ["Segmento de división de red", "Subgrupo de dirección IP", "Partición de red"],
    "supercomputadora": ["Computadora de alto rendimiento", "Sistema de cálculo avanzado", "Máquina de cálculo científico"],
    "soporte": ["Servicio de asistencia técnica", "Ayuda de resolución de problemas", "Provisión de ayuda al usuario"],
    "sintaxis": ["Gramática del lenguaje de programación", "Reglas de estructura de código", "Especificación de formato de lenguaje"],
    "sistema": ["Colección integrada de tecnología", "Conjunto coordinado de componentes", "Configuración de computadora organizada"],

    # T (60 términos)
    "typescript": ["JavaScript con tipos", "Lenguaje de programación Microsoft", "Superconjunto tipado de JS"],
    "tableta": ["Dispositivo portátil con pantalla táctil", "Plataforma informática móvil", "Computadora de mano"],
    "etiqueta": ["Marcador de etiqueta de contenido", "Categorización de información", "Identificación de datos"],
    "tarea": ["Unidad de trabajo informático", "Trabajo de ejecución de programa", "Operación del sistema"],
    "plantilla": ["Patrón de formato de documento", "Estructura de diseño reutilizable", "Diseño preelaborado"],
    "prueba": ["Proceso de verificación de software", "Método de verificación de calidad", "Procedimiento de detección de errores"],
    "hilo": ["Ruta de ejecución de programa", "Secuencia de procesamiento", "Línea de tarea concurrente"],
    "token": ["Objeto de acceso de seguridad", "Pieza de autenticación", "Unidad de permiso digital"],
    "herramienta": ["Programa de utilidad de software", "Aplicación de asistencia de desarrollo", "Ayudante técnico"],
    "pantalla táctil": ["Interacción directa de visualización", "Tecnología de interfaz táctil", "Entrada de contacto con pantalla"],
    "transacción": ["Unidad de operación de base de datos", "Acción de proceso comercial", "Intercambio completo de datos"],
    "transmisión": ["Proceso de envío de datos", "Transferencia de información", "Comunicación de red"],
    "solución de problemas": ["Proceso de resolución de problemas", "Método de resolución de incidencias", "Diagnóstico de fallas"],
    "tupla": ["Secuencia ordenada de datos", "Colección de elementos fija", "Estructura de datos de programación"],
    "twitter": ["Plataforma de redes sociales", "Servicio de microblogging", "Red de mensajes cortos"],
    "tipo": ["Clasificación de categoría de datos", "Tipo de variable de programación", "Formato de información"],

    # U (40 términos)
    "interfaz de usuario": ["Interfaz de Usuario", "Diseño visual de aplicación", "Superficie de interacción del usuario"],
    "experiencia de usuario": ["Experiencia de Usuario", "Calidad general de interacción del usuario", "Diseño de interacción humano-computadora"],
    "ubuntu": ["Sistema operativo Linux", "Distribución OS de código abierto", "Linux basado en Debian"],
    "carga": ["Envío de datos al servidor", "Transferencia de archivo a sistema remoto", "Compartición de información a red"],
    "url": ["Ubicación de dirección web", "Localizador de Recursos Uniforme", "Identificador de sitio de internet"],
    "usb": ["Bus Serie Universal", "Estándar de conexión de dispositivos", "Interfaz de periféricos de computadora"],
    "usuario": ["Persona operadora del sistema", "Consumidor de software", "Usuario final de tecnología"],
    "agente de usuario": ["Software que actúa para usuario", "Identificación de navegador", "Aplicación cliente"],
    "historia de usuario": ["Descripción de requisito de desarrollo", "Formato de explicación de característica", "Herramienta de desarrollo ágil"],
    "utilidad": ["Programa asistente del sistema", "Aplicación de herramienta informática", "Programa de asistencia de software"],

    # V (40 términos)
    "máquina virtual": ["Emulación de computadora por software", "Entorno virtualizado", "Sistema operativo invitado"],
    "vpn": ["Red Privada Virtual", "Conexión a internet segura", "Túnel de red cifrado"],
    "virus": ["Programa informático malicioso", "Software malicioso auto-replicante", "Código de infección digital"],
    "realidad virtual": ["Entorno digital inmersivo", "Mundo generado por computadora", "Experiencia simulada VR"],
    "control de versiones": ["Gestión de cambios de código", "Seguimiento de revisión de software", "Sistema de historial de desarrollo"],
    "video": ["Contenido visual en movimiento", "Imágenes en movimiento digitales", "Animación electrónica"],
    "reconocimiento de voz": ["Tecnología de comprensión del habla", "Procesamiento de comandos de voz", "Interpretación de entrada de audio"],
    "vulnerabilidad": ["Punto de debilidad de seguridad", "Exposición de falla del sistema", "Oportunidad de ataque cibernético"],
    "validación": ["Verificación de exactitud de datos", "Proceso de verificación de entrada", "Confirmación de precisión de información"],
    "variable": ["Contenedor de datos de programación", "Ubicación de almacenamiento de valor", "Poseedor de información cambiable"],

    # W (50 términos)
    "desarrollo web": ["Proceso de creación de sitio web", "Construcción de aplicación en línea", "Desarrollo de software de internet"],
    "sitio web": ["Colección de ubicaciones de internet", "Grupo de páginas web", "Sitio de presencia en línea"],
    "windows": ["Sistema operativo Microsoft", "Plataforma de escritorio PC", "Entorno OS gráfico"],
    "inalámbrico": ["Conexión sin cables", "Redes basadas en radio", "Tecnología sin cables"],
    "flujo de trabajo": ["Automatización de secuencia de procesos", "Sistema de procedimiento de tareas", "Gestión de procesos de negocio"],
    "servidor web": ["Proveedor de contenido de internet", "Computadora de alojamiento de sitio web", "Sistema de servicio en línea"],
    "aplicación web": ["Software basado en navegador", "Interfaz de programa en línea", "Aplicación accesible por internet"],
    "wi-fi": ["Tecnología de redes inalámbricas", "Conexión a internet por radio", "Red de área local inalámbrica"],
    "gusano": ["Software malicioso auto-propagador", "Virus que se extiende por red", "Código malicioso replicante"],
    "diseño web": ["Creación visual de sitio web", "Diseño de interfaz en línea", "Diseño de página de internet"],
    "alojamiento web": ["Servicio de almacenamiento de sitio web", "Provisión de contenido en línea", "Alquiler de sitio internet"],
    "servicio web": ["Componente de software en línea", "Función accesible por internet", "Servicio API web"],
    "web socket": ["Comunicación web en tiempo real", "Protocolo de conexión persistente", "Intercambio de datos en vivo"],
    "sombrero blanco": ["Hacker de seguridad ético", "Probador de penetración autorizado", "Hacker de buena intención"],
    "widget": ["Elemento de componente de interfaz", "Objeto de control GUI", "Pieza de programa visual"],
    "wiki": ["Plataforma de sitio web colaborativo", "Contenido editable por comunidad", "Base de conocimiento grupal"],
    "wireframe": ["Boceto de diseño de interfaz", "Estructura de diseño básica", "Esquema de planificación visual"],
    "estación de trabajo": ["Sistema de computadora profesional", "Escritorio de alto rendimiento", "Estación informática especializada"],
    "world wide web": ["Sistema de información global", "Red de contenido de internet", "Colección de páginas web"],

    # X (10 términos)
    "xml": ["Lenguaje de Marcado Extensible", "Estándar de formato de datos", "Formato de documento estructurado"],
    "xss": ["Ataque de cross-site scripting", "Vulnerabilidad de seguridad web", "Ataque de inyección de navegador"],
    "xcode": ["Entorno de desarrollo Apple", "IDE de programación iOS", "Constructor de aplicación Mac"],
    "xamarin": ["Framework móvil Microsoft", "Desarrollo de aplicación multiplataforma", "Programación móvil C#"],
    "xhtml": ["Versión HTML extendida", "Estándar HTML estricto", "HTML basado en XML"],

    # Y (10 términos)
    "yaml": ["Formato de datos legible por humanos", "Lenguaje de archivo de configuración", "Estándar de serialización de datos"],
    "youtube": ["Plataforma de compartir video", "Servicio de video en línea", "Sitio de video de Google"],

    # Z (10 términos)
    "día cero": ["Vulnerabilidad de software desconocida", "Defecto de seguridad no parcheado", "Exploit recién descubierto"],
    "zip": ["Formato de compresión de archivos", "Formato de archivo de datos", "Formato de archivo comprimido"],
    "zombie": ["Sistema informático comprometido", "Máquina controlada por botnet", "Dispositivo de red pirateado"]
}